### ISSUE TITLE
hilite in editor

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#10]
Wish
- фон фрагм- ставить как ed.get_prop(PROP_COLOR, цвет_фона)
- цвет как цвет текста
- ставить зеленый underline (синий? фиолет?)

**Comment by kvichans** [comment]
Попробовал несколько способов. Остановился на мягком подчеркивании
![hi_text](https://cloud.githubusercontent.com/assets/7419630/14464678/80fc77b8-00d8-11e6-94a4-f5da6615e4d5.JPG)

**Comment by Alexey-T** [comment]
У вас цвет черный. надо цвет текста

**Comment by kvichans** [comment]
После перехода с умолчания 0 на COLOR_NONE сам появится

**Comment by kvichans** [comment]
а-а-а! Понял. Todo

**Comment by kvichans** [comment]
Уточните, какой цвет у бордюра, если ставить COLOR_NONE? Может он уже цвет текста?

**Comment by Alexey-T** [comment]
Рамке и тексту надо об.цвет (не none)

**Comment by kvichans** [comment]
Согласен, что _часто_ рамку и текст нужно показывать общим цветом.
Вопрос: кто это должен отслеживать?
Что мешает Куд самому это делать, если для обоих задан COLOR_NONE?

**Comment by Alexey-T** [comment]
это дoлжен делать FinF, color_none нет для color_font/color_border

**Comment by kvichans** [comment]
Зачем плагину, который хочет **лишь показать** рамку залазить в потроха конфигурации и выяснять какой там цвет у текста и выставлять его для рамки. Абсурд!

**Comment by Alexey-T** [comment]
нет, вы читаете цвет текста (PROP_COLOR). Его ставить фонту+ рамке

**Comment by kvichans** [comment]
Согласен, я _могу_ это сделать
Не согласен, что я _должен_ это делать каждый раз, если это можно переложить на Куд.
Если вы это не сделаете, я сделаю патч для cudatext.py и буду вносить в `def attr` эти действия при каждом его обновлении

**Comment by kvichans** [comment]
Надеюсь мы найдем компромис

**Comment by Alexey-T** [comment]
правильно что надо задать цвет. Потому что часто цвет фонта надо необычн, и цвет рамки тоже

**Comment by kvichans** [comment]
Не правильно, что цвет рамки и текста нужно задавать **всегда**

**Comment by kvichans** [comment]
Давайте я сделаю патч, а вы либо примете его, либо я буду им один пользоваться?

**Comment by Alexey-T** [comment]
а по-моему, это ОК. не патч, можете сделать wrapper

**Comment by kvichans** [comment]
Мне не ясна причина вашего сопротивления.
Я хочу внести изменения в `def attr` из `cudatext.py`. Почему эти изменения не нужны остальным?

**Comment by Alexey-T** [comment]
Какой патч?

**Comment by kvichans** [comment]
Перенос значения ed.get_prop(PROP_COLOR, цвет_текста) в цвета рамок и текста, если они заданы как COLOR_NONE

**Comment by Alexey-T** [comment]
покажите

**Comment by kvichans** [comment]
```
    def attr(self, id, tag=0, x=0, y=0, len=0,
             color_font=COLOR_NONE, color_bg=COLOR_NONE, color_border=COLOR_NONE,
             font_bold=0, font_italic=0, font_strikeout=0,
             border_left=0, border_right=0, border_down=0, border_up=0
             ):
        if color_font==COLOR_NONE:
            color_font=ed.get_prop(PROP_COLOR, COLOR_ID_TextFont)
        if color_border==COLOR_NONE:
            color_border=ed.get_prop(PROP_COLOR, COLOR_ID_TextFont)
        return ct.ed_attr(self.h, id, tag, x, y, len,   
                          color_font, color_bg, color_border,
                          font_bold, font_italic, font_strikeout,
                          border_left, border_right, border_down, border_up
                          )
```

**Comment by Alexey-T** [comment]
Надо ставить import cudatext_colors - плохо, или констант-строку (color_id)

**Comment by kvichans** [comment]
- Зачем 43 константы выделены из `cudatext.py` в `cudatext_colors.py`?
- Если вам import "плохо", то почему для плагина это хорошо, если ему цвета не нужны?

**Comment by Alexey-T** [comment]
видимо можно вмержить в 1 файл. Погляжу

**Comment by Alexey-T** [comment]
пач ок. Done

**Comment by kvichans** [comment]
Уф-ф.
