### ISSUE TITLE
strange looks: [xxx]Adv

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#100]
What it means? [xxx] etc
![xx](https://cloud.githubusercontent.com/assets/4154978/21542601/5bfaa0c0-cdd8-11e6-89ff-4d566ecb5d9e.png)

**Comment by kvichans** [comment]
Это условное обозначение для перечисления какие опции будут восстанавливаться.
Например, подпись `.*aAw` - это про три разные галки, а `[xxx]` означает, что они все будут восстановлены
