### ISSUE TITLE
Fedora contrls are high

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#101]
дублирую.
Оч. большие контролы
На всех плагинах так (напр Make Plugin)

![fedr](https://cloud.githubusercontent.com/assets/4154978/21543698/388c9cec-cde2-11e6-9199-c3b45583bbad.png)

**Comment by kvichans** [comment]
fix бета 
проверьте

**Comment by Alexey-T** [comment]
еще бы на 4-6 пкс побольше combo.

**Comment by kvichans** [comment]
Лучше снимок - на словах не понятно

**Comment by Alexey-T** [comment]
![fed2](https://cloud.githubusercontent.com/assets/4154978/21557407/1bf6ab64-ce45-11e6-97c4-8a0d21965a23.png)

**Comment by kvichans** [comment]
Да уж! Придется раскладку для Лина отщепить от раскладки для Вина.
В Вин будет плотная укладка, а в во всех Линах - рыхлая.

**Comment by kvichans** [comment]
Fix
Для Вин стало плотнее:
![fif-w32](https://cloud.githubusercontent.com/assets/7419630/21561147/ce2c77e4-ce79-11e6-90ea-5fd643d428f9.PNG)

Для Лин стало рыхлее:
![fif-lin](https://cloud.githubusercontent.com/assets/7419630/21561148/ce2dccde-ce79-11e6-8b52-c3927e2c483c.PNG)

Попробуйте в Федоре.

**Comment by Alexey-T** [comment]
стало лучше. Спасибо
