### ISSUE TITLE
Beta: v 1.2.6 Right aligned label, image in help  

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#106]
Небольшой редизайн.
![fif-r-algn png](https://cloud.githubusercontent.com/assets/7419630/23266687/8f32d758-f9f9-11e6-8ff7-97882a5bdf52.png)

В диалоге Help появилась картинка со всеми хинтами к кнопкам основного диалога
![fif-help-img png](https://cloud.githubusercontent.com/assets/7419630/23266688/8f34f0ba-f9f9-11e6-9d96-dc78911c14e8.png)

**Comment by Alexey-T** [comment]
Да, очень хорошо, спс, labels смотрятся нормально

**Comment by kvichans** [comment]
Картинки вставляются :)
Скоро нужны будут картинки с откликом: 
- либо аналоги `linklabel`
- либо кнопки с картинкой вместо текста

**Comment by Alexey-T** [comment]
да, можно сделать такие контролы, Ок.
