### ISSUE TITLE
empty Keys help in 1.2.8

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#109]
I see empty half of dialog
![img-no](https://cloud.githubusercontent.com/assets/4154978/24160963/38c2134a-0e74-11e7-9118-1eaafeb8a4ad.png)

**Comment by Alexey-T** [comment]
Такого файла у меня нет-  папки images тоже- `items=/home/user/cuda/cuda/app/py/cuda_find_in_files/images/fif-hints_770x400.PNG`

**Comment by kvichans** [comment]
Да, забыл при публикации добавить папку `images`. Исправил
