### ISSUE TITLE
keys help needs details: B, Kb, Mb

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#114]
// Size of buffer (at file start) to detect binary files
    "fif_read_head_size":1024,

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Может достаточно заменить имя ключа на 
`  "fif_read_head_size(bytes)":1024`
?

**Comment by Alexey-T** [comment]
Можно написать в комменте- что байты..
