### ISSUE TITLE
Beta v1.2.9: New config keys, new dlg

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#115]
1. Имя ключа `fif_read_head_size` заменено (без потерь) на `fif_read_head_size(bytes)`.

2. Добавлены два ключа `fif_context_width_before` и `fif_context_width_after` для индивидуального управления числом доп.строк попадающих в отчет. Умолчания для их значений либо 1, либо значение прежнего ключа `fif_context_width`.

3. В основном диалоге добавлен перехват включения галки `[x]Contex` с удержанием `Ctrl` - появляется диалог
![report context settings](https://cloud.githubusercontent.com/assets/7419630/24246827/2838bc06-0fda-11e7-9ee6-3393e723423b.png)

**Comment by Alexey-T** [comment]
1)
```
     "fif_context_width":1,
+    "fif_context_width_before":1,
+    "fif_context_width_after":1,
```
Если есть новые 2 опции,то опция перед ними не нужна.

2) Настройка этих опц-- лучше ее не в ctrl-click, это checkbox,
его криво делать активным.
Можно дать в adjust

**Comment by kvichans** [comment]
Не согласен по обоим пунктам
1. Можно не задавать новые `fif_context_width_*` и продолжать пользоваться старым `fif_context_width`
2. Эти опции к Adjust не относятся. По-хорошему, нужно сделать новый большой диалог для всех опций, которые сейчас берутся из `user.json`. Проблема ровно такая же как у Куд в целом: нужен "богатый" диалог a la Properties, которого еще нет.

**Comment by Alexey-T** [comment]
OK, тода эти виши снимаются
