### ISSUE TITLE
Size of dialog Help

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#116]
Высота диалога Help оч большая-- у меня на ноуте уместился еле еле, на многих ноутах не уместится

**Comment by kvichans** [comment]
700 много?
Разве еще не вымерли "мамонты" с экранами меньше 800?

**Comment by Alexey-T** [comment]
нет, и если VM (virtualbox) внутри ноутбука, то мало места в vm.

**Comment by kvichans** [comment]
И как понять "допустимый" размер?

**Comment by Alexey-T** [comment]
Если сейчас 700, то 650..600 будет ОК

**Comment by kvichans** [comment]
Посмотрю, что можно сделать

**Comment by Alexey-T** [comment]
Mac book 2008г-
для диалога только верх.край кнопок виден
(сами кнопки под таскбаром)

**Comment by Alexey-T** [comment]
точнее, полоска- рамка memо видна, а край кнопок уже нет.

**Comment by Alexey-T** [comment]
Плс, можно для Мака это поправить?

**Comment by kvichans** [comment]
Будет для всех

**Comment by kvichans** [comment]
fixed
