### ISSUE TITLE
Replace: dont work

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#120]
Поиск идет
```
+Search for "ssExtra1" in "/home/user/cuda/synedit" (3 matches in 1 files)
	</home/user/cuda/synedit>: #3
		<atsynedit>: #3
			<atsynedit.pas>: #3
				<(1170)>:     property OptMouseWheelScrollHorzWithState2: TShiftStateEnum read FOptMouseWheelScrollHorzWithState2 write FOptMouseWheelScrollHorzWithState2 default ssExtra1;
				<(2669)>:   FOptMouseWheelScrollHorzWithState2:= ssExtra1;
				<(3795)>:      (Shift=[FOptMouseWheelScrollHorzWithState2]) then //ssExtra1 is set in new LCL 1.7 patch
```

замена не идет. отчета нет.
Потом находит опять ssExtra1

![ex-rep](https://cloud.githubusercontent.com/assets/4154978/24827749/af930050-1c58-11e7-8b95-cafd4dc729e6.png)

**Comment by kvichans** [comment]
Нужен переносимый пример:
- создать новую папку
- туда положить файлы для поиска/замены
- добиться повторения проблемы
- передать папку и файл settings\cuda_find_in_files.json (изменения путей на свои я сам сделаю)

**Comment by Alexey-T** [comment]
- Скачать репо https://github.com/graemeg/lazarus
- искать в папке lcl в репо

**Comment by Alexey-T** [comment]
Пример 2

- скачать репо https://github.com/Alexey-T/ATSynEdit
- искать в папке репо

**Comment by kvichans** [comment]
В репо ATSynEdit поиск `ssExtra1` (при `[x]"w"`) среди `*.pas *.pp *.inc` ничего не находит.

**Comment by Alexey-T** [comment]
Там уже поменялось- нет строки ssExtra1
попробую на другой

**Comment by Alexey-T** [comment]
В папке gtk ищем
GDK_SHIFT_MASK
находится.
делаем замену как на скрине. не меняется. 
[gtk.zip](https://github.com/kvichans/cuda_find_in_files/files/909638/gtk.zip)
![rep22](https://cloud.githubusercontent.com/assets/4154978/24855899/9e37bca8-1deb-11e7-846d-08c8dba4651a.png)

**Comment by kvichans** [comment]
повторил

**Comment by kvichans** [comment]
Забавная ошибка из-за копипейста:
```
            if app.ID_YES != app.msg_box('Do you want to replace?, 
                ,app.MB_OKCANCEL+app.MB_ICONQUESTION):
                continue
```
Должно быть `if app.ID_OK !=`
