### ISSUE TITLE
v 1.2.11 Editor for options

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#121]
1. Добавлена команда (без отображения в меню)
`Find in Files\View and edit options...`
для вызова редактора опций из `user.json`.

2. В диалог `Help` на вкладке `Opts` добавлена кнопка для вызова этого же редактора
![help for find in files - ed4ops](https://cloud.githubusercontent.com/assets/7419630/24868163/e143724a-1e17-11e7-8d92-2530064dd853.png)

3. Появляется такой редактор с опциями в четырех секциях
![fif options 1 1 12](https://cloud.githubusercontent.com/assets/7419630/24868162/e13f0584-1e17-11e7-9712-8edff8c5bbda.png)

4. Опции помечены 17 тегами
![fif ops tags 17](https://cloud.githubusercontent.com/assets/7419630/24868167/e181eed0-1e17-11e7-96c6-aed5ccf005a9.png)

**Comment by Alexey-T** [comment]
IMO

- кнопка Open user.json не нужно (есть и так кмд)
- команду надо в меню plugins
-  сепаратором - выделить часть п-тов для настройки -в plugins

**Comment by kvichans** [comment]
- Да, теперь не нужна
- Спорно. Зачем?
- Не понял

**Comment by Alexey-T** [comment]
теги кривые -

- findind
- enternal- что это...

**Comment by kvichans** [comment]
- findind - ключ относится к настройке поиска
- enternal - ключ для настройки внутреннего поведения

**Comment by Alexey-T** [comment]
tag start/stop- Можно делать  1 тег start_stop.

**Comment by kvichans** [comment]
Ага. Похоже вы не осознаете, что **много** разных тегов (в отличии от секций) это хорошо

**Comment by Alexey-T** [comment]
Таких слов нету просто- findind enternal

**Comment by kvichans** [comment]
internal - конечно, описка

**Comment by Alexey-T** [comment]
ОК- только слова поправить

**Comment by Alexey-T** [comment]
findind тоже описка.

**Comment by kvichans** [comment]
searching - конечно

**Comment by Alexey-T** [comment]
У вас finding+ searching

**Comment by kvichans** [comment]
теперь будет только searching и internal

**Comment by Alexey-T** [comment]
"не понял"- сделать 2 команды  настроек в pluygins- Mouse clicks/ Options

**Comment by kvichans** [comment]
добавлю о меню

**Comment by kvichans** [comment]
Нормально?:
![fif menu](https://cloud.githubusercontent.com/assets/7419630/24871841/b0ed61a8-1e23-11e7-82c9-369c7c6b2a32.png)

**Comment by Alexey-T** [comment]
Лучше назвать 1й
Configure mouse clicks...

**Comment by kvichans** [comment]
Не убедили

**Comment by Alexey-T** [comment]
Слово Configure - а не configurate

**Comment by kvichans** [comment]
Спасибо
