### ISSUE TITLE
Log opts

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#123]
Можно назвать все опц как fif_log_*?

![fiflog](https://cloud.githubusercontent.com/assets/4154978/24872507/56e8580e-1e26-11e7-8de5-11e0b2593129.png)

**Comment by kvichans** [comment]
Нет. Текущий стиль коряв, но у него крепкие корни

**Comment by Alexey-T** [comment]
Вы про такое говорите "бред", сори.
