### ISSUE TITLE
v 1.2.12 Hidden opts in title

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#124]
1. Раскрытый вид
- Удалена настройка отчета Collect.
- Добавлена горизонтальная черта-разделитель
![find in files 1 2 12 full](https://cloud.githubusercontent.com/assets/7419630/24913464/efa18bac-1ed9-11e7-9403-8da8bed4943f.png)

2. Свернутый вид
- Добавлено отображение невидимых настроек в титуле
![find in files 1 2 12 compact](https://cloud.githubusercontent.com/assets/7419630/24913554/2c98d09c-1eda-11e7-9378-e5bc870978eb.png)

**Comment by Alexey-T** [comment]
OK, проверил свернутый вид

**Comment by kvichans** [comment]
Спасибо.
Поменял цвет линии-разделителя на серый.
Публикую...
