### ISSUE TITLE
v 1.2.13 New hotkeys to set depth

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#125]
![dept-hint](https://cloud.githubusercontent.com/assets/7419630/24949857/b5d3412e-1f77-11e7-98c8-1250e70a1e77.PNG)
Также как и хоткеи `Alt+1`, `Alt+2`, `Alt+3`, для Пресетов, эти `Alt+L`, `Alt+Y` реализованы через невидимые (ширина=0) кнопки.

**Comment by Alexey-T** [comment]
>реализованы через невидимые (ширина=0) кнопки.

Думал добавить видимость. уже есть en=, добавить visible= (0/1).

**Comment by kvichans** [comment]
Ширина=0 и так справляется с этой задачей

**Comment by kvichans** [comment]
Есть опасность, что при  visible=0 не будет срабатывать хоткей.

**Comment by Alexey-T** [comment]
Да, не срабатывает при visible=false.
