### ISSUE TITLE
artefacts on left side

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#127]
Buttons edge?
![fif-left](https://cloud.githubusercontent.com/assets/4154978/25225589/93957f7e-25ca-11e7-8fd4-9d4a24a5feae.png)

**Comment by kvichans** [comment]
Подозрение на мои скрытые контролы. 
Для проверки нужно закомментировать в cd_fi_in_fi.py пять строк, содержащих
`,tp='bt'      ,tid='incl'     ,l=0        ,w=0` (3 шт)
`,tp='bt'      ,tid='dept'     ,l=0        ,w=0` (2 шт)

**Comment by Alexey-T** [comment]
думаю это они. Можно дать им x=-5..

**Comment by kvichans** [comment]
Проверили?
Я поставлю x=-10, но это "ловля кота в темноте"

**Comment by kvichans** [comment]
Опа! Оказалось, что такая замена не скрывает!

**Comment by kvichans** [comment]
Поставил x=1000

**Comment by kvichans** [comment]
Помогло?

**Comment by Alexey-T** [comment]
Да, помогло
