### ISSUE TITLE
count of result limited by 100 items?

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#128]
http://synwrite.sourceforge.net/forums/viewtopic.php?f=5&t=1799&sid=

**Comment by kvichans** [comment]
Я не понял проблему.
@Alexey-T Может вы поняли? Может так какая-то тонкость английского?

**Comment by Alexey-T** [comment]
Рез-ты поиска показывают максимум 100 штук

..не подтвердил.

**Comment by Alexey-T** [comment]
не подтвердил.

**Comment by kvichans** [comment]
А почему noutters два раза пишет про copy и copying ?

**Comment by Alexey-T** [comment]
не знаю...
