### ISSUE TITLE
Gray line; version

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#130]
Установил 1.2.14- в титуле все равно 1.2.12

Линия для adv options черная- лучше серую

**Comment by kvichans** [comment]
"Установил"? Из ГХ или менеджером?

**Comment by kvichans** [comment]
Линия раньше была уже серая. Я не менял код. Могу передать полный text для dlg_custom. В нем для этой линии есть такой фрагмент: `font=default,9,12171705`.
Что изменилось в Куд?

**Comment by Alexey-T** [comment]
из Addonman Updater.
![fif](https://cloud.githubusercontent.com/assets/4154978/25326547/5b2119c0-28d9-11e7-80d9-15da80dc5216.png)

**Comment by kvichans** [comment]
Для менеджера, то есть из СФ, версия еще не обновлялась.
ToDo: версии проверю, поправлю

**Comment by kvichans** [comment]
Линия рисуется таким фрагментом `text`:
`type=labelcap=———————font=default,9,12171705pos=0,140,659,0`
Почему Куд не показывает (перестал показывать!) ее серой?

**Comment by Alexey-T** [comment]
потому что "font=" убран,
надо "font_name", "font_color".

**Comment by kvichans** [comment]
Нужно переделать конфигуратор user.json

**Comment by kvichans** [comment]
В вики ничего не сказано про удаление свойства font
А еще в вики указано
```
add: dlg_proc: control type "treeview"
add: dlg_proc: control type "listbox_ex"
add: dlg_proc: control type "trackbar"
add: dlg_proc: control type "progressbar" 
```
Правильно я понимаю, что тут **пропущен** dlg_custom?

**Comment by kvichans** [comment]
Изменения ломающие работающие программы - большое зло. Зачем было убивать font?

**Comment by Alexey-T** [comment]
Wiki поправил, спсб
Да, пропущен dlg_custom
