### ISSUE TITLE
Config presets er

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#134]
В окне 2 пресета
жму move down
=> пресеты пропали в listbox, ..... потом Куд вылетел

**Comment by kvichans** [comment]
До MoveDown что-то еще делали?

**Comment by Alexey-T** [comment]
нет.

**Comment by kvichans** [comment]
Не повторил

**Comment by Alexey-T** [comment]
(тест под Убунту, посм. в виртуалке)

**Comment by Alexey-T** [comment]
config 
[cuda_find_in_files.zip](https://github.com/kvichans/cuda_find_in_files/files/964784/cuda_find_in_files.zip)

**Comment by kvichans** [comment]
В этом файле нет пресетов

**Comment by kvichans** [comment]
Нужно сделать копию ДО сбоя

**Comment by Alexey-T** [comment]
Только этот файл есть,не менялся

**Comment by kvichans** [comment]
>В окне 2 пресета

>В этом файле нет пресетов

Не сходятся факты

**Comment by Alexey-T** [comment]
не знаю. в окне -два пресета.

**Comment by Alexey-T** [comment]
![pre](https://cloud.githubusercontent.com/assets/4154978/25535837/27809d14-2c41-11e7-97e1-529a1fb7f843.png)

**Comment by kvichans** [comment]
значит файл не тот

**Comment by Alexey-T** [comment]
Не та Куда
