### ISSUE TITLE
Help hangs

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#135]
Help dlg:

- кликаем мемо. печать 2-3 букв. 
- клик любой кнопки внизу- ничего не меняется
- ....10сек- Куд вылетел

**Comment by kvichans** [comment]
Проблема только на вашей стороне

**Comment by Alexey-T** [comment]
Непонятно в чем проблема

**Comment by Alexey-T** [comment]
Сори это копия не новая куды
