### ISSUE TITLE
'Save as preset'- crash

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#136]
"Save preset" выбор крешится

![pre--](https://cloud.githubusercontent.com/assets/4154978/25547838/224bd062-2c72-11e7-9e88-c628fbdde73d.png)

**Comment by kvichans** [comment]
Не повторил

**Comment by Alexey-T** [comment]
если я могу вкл. лог для SavePresetAs то может поможет найти.

**Comment by kvichans** [comment]
Выложил код с включенным логом
1. Нужно в user.json дать
`"fif_LOG":true,`
2. Мой лог получается такой
```
[ 0.01"]dlg_press:317 ps_ind=3
[ 0.02"]dlg_press:488 ps_ind=3
[ 0.03"]dlg_wrapper:381 in_vals={'name': '#2: "*.pas *.pp *.inc" in "~/lazarus/lcl/interfaces/carbon"',
 'what': (0, ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'])}
[ 0.05"]dlg_wrapper:505 app.dlg_custom("Save preset",310,510,open(r"g:\Temp\dlg_custom_ctrls.txt",encoding="UTF-8").read(), 1)
```

**Comment by kvichans** [comment]
3. Во временную папку пишется `dlg_custom_ctrls.txt`
4. Это позволяет повторить вызов с помощь
`dlg_custom("Save preset",310,510,open(r"g:\Temp\dlg_custom_ctrls.txt",encoding="UTF-8").read(), 1)`

**Comment by Alexey-T** [comment]
Спасибо. теперь на этой в-и нет креша.

**Comment by kvichans** [comment]
Это очень плохо! Версия отличается только логом

**Comment by kvichans** [comment]
Удалось что-то понять?

**Comment by Alexey-T** [comment]
нет `:\`, на втором ПК тоже работает.

**Comment by kvichans** [comment]
Поразительно! У вас у руках есть воспроизводимая проблема, а вы закрываете глаза. Эта бомба обязательно взорвется, но не факт, что вы сможете воспроизвести ее взрыв в следующий раз.

**Comment by Alexey-T** [comment]
наверное так. У меня на 2м пк есть 2 куды. в однойй креш. Обновил ФИФ до ГХ.
до 1.3.
теперь креша нет.
(не помню версию ФИФ до обновления.)

**Comment by kvichans** [comment]
Разница последней ГХ-версии ФИФ и предыдущей только в логах.
В чем проблема достать "предыдущую" из репо?

**Comment by Alexey-T** [comment]
Кажется на второй Куде был более старый Фиф

**Comment by kvichans** [comment]
На моей Вин-платформе краши исчезли. На Лин - вам виднее.

**Comment by Alexey-T** [comment]
креш на новой версии. скрин. конфиг.

![fif](https://cloud.githubusercontent.com/assets/4154978/25635583/4f68383e-2f87-11e7-9dc7-0af3550d4003.png)

[cuda_find_in_files.zip](https://github.com/kvichans/cuda_find_in_files/files/971782/cuda_find_in_files.zip)

**Comment by kvichans** [comment]
С вашими настройками у меня отрабатывает штатно.
![save preset](https://cloud.githubusercontent.com/assets/7419630/25638479/3af7f02e-2f91-11e7-9da6-687338f71447.png)

**Comment by Alexey-T** [comment]
не крешится уже.
