### ISSUE TITLE
Use control "bevel"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#137]
..контрол есть в релизе Куд.
Пока на маке так- линия в ФИФ видна как серые минусы (неплотно)
С бевелом- будет ок.

**Comment by kvichans** [comment]
Поясните `4 sides` в описании
`"bevel": only line, w/o value, w/o caption (at 1 side or at all 4 sides) `

Это можно сделать рамкой для группы контролов?
Можно ли на эту рамку наложить label?

**Comment by kvichans** [comment]
Нужны подробности для свойства `prop`  у `bevel`:
`int_shape (0: box, 1: frame, 2: top line, 3: bottom line, 4: left line, 5: right line, 6: empty spacer)`

**Comment by kvichans** [comment]
Чем `box` отличается от `frame`?
Чем `top/left line` отличается от `bottom/rigth line`?
Что такое `empty spacer`?

**Comment by Alexey-T** [comment]
Написал подробнее, ок?

**Comment by kvichans** [comment]
Стало не намного яснее. 
- Чем `left line` от `rigth line`?
- Зачем нужен `6: no lines`?

И можно ли наложить сверху подпись?

**Comment by Alexey-T** [comment]
Линия на левом или правом крае у контрола. Наложить не пробовал

**Comment by Alexey-T** [comment]
No lines был в Лазе

**Comment by kvichans** [comment]
Совсем запутали!
Пока речь была про **линию** для замены `type=label,val='-----'` еще можно было догадываться, что новый контрол это какая-то линия.
А теперь уже у него появились правые и левые края.
Дайте примеры

**Comment by Alexey-T** [comment]
Контрол это rect, у него или все края или только один край

**Comment by Alexey-T** [comment]
Если нет краев то показан как empty space

**Comment by kvichans** [comment]
- Есть "sunken panel" ("притопленный"?), но нет к нему парного "приподнятый"
- Можно отобразить только одну сторону прямоугольника `2: top line, 3: bottom line, 4: left line, 5: right line`, но этими константами нельзя описать отображение двух или трех сторон

Совсем не понятно, является ли этот прямоугольник "прозрачным", то есть скроет ли он контролы под собой. Можно ли поверх него ставить другие контролы?

**Comment by Alexey-T** [comment]
- да, поднятого нету
- да, 2-3и стороны нельзя

Да- он прозрачный -
![be](https://cloud.githubusercontent.com/assets/4154978/25615889/698194d0-2f42-11e7-96e3-de7fc190c364.png)

**Comment by kvichans** [comment]
В целом ясно - это рамка.
Вот бы ей еще встроенную подпись, это было бы классно. 
Если же соединять эту рамку с label, то невозможно угадать ширину подписи, она же скачет при смене платформы. Будет получаться так
`------- Подпись                     -----------`
Нет ли в Лазарусе у label свойства _автоширина_?

**Comment by kvichans** [comment]
Вы показали как выглядит "прозрачный" в дизайн-режиме. А как это выглядит при запуске? Подозреваю, что по-другому

**Comment by Alexey-T** [comment]
auto-width для label уже включен.

**Comment by kvichans** [comment]
Пробую сделать рамки с подписями для ФИФ "Adv...opts"

**Comment by kvichans** [comment]
В бете cudatext-win-x64-1.8.3.0 этого типа контрола еще нет?

**Comment by kvichans** [comment]
Нашел в релизе

**Comment by kvichans** [comment]
Не получается дать подпись. При `prop='1'` это выглядит так
![find in files 1 3 01 - frame](https://cloud.githubusercontent.com/assets/7419630/25618096/30fb1ad0-2f4e-11e7-8651-5fd9685bfb80.png)

1. Можно ли сделать рамку непрозрачной? Будут ли работать контролы добавленные позже?
2. Можно ли избавиться от стиля линий sunken?

**Comment by Alexey-T** [comment]
1,2: нельзя, но можно лабел поместить выше

**Comment by kvichans** [comment]
Нет, не подходит.
- Подпись нужно ставить ПОД рамкой, так как высота подписи разная по платформам
- Выглядит убого
![find in files 1 3 01 2frames](https://cloud.githubusercontent.com/assets/7419630/25621072/f123a5de-2f58-11e7-8341-b63c9cbe3f1d.png)

В таком виде рамкой пользоваться не буду.
Линию вместо ------ через новый контрол сделаю. Но ее стиль (sunken) выбивается из стилей остальных элементов. Не приятно

**Comment by kvichans** [comment]
Из-за стиля sunken я подозреваю, что нельзя для bevel назначить color. Так?

**Comment by Alexey-T** [comment]
> так как высота подписи разная по платформам

Можно и подпись после рамки  создать. (font size примерно один на ОСах)

**Comment by Alexey-T** [comment]
color -не пробовал. наверное нельзя

**Comment by Alexey-T** [comment]
3: Можете  сделать 1-pixel colorpanel

**Comment by kvichans** [comment]
Да, с bevel ничего путного не получилось. Жаль! Рамка с подписью нужна.
Сделаю линию из colorpanel.
