### ISSUE TITLE
dlg "send values" puts FIF to back, Linux

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#138]
скрин не вст-тся.
При показе send values to email--- FIF dlg помещается сзади Куды

**Comment by kvichans** [comment]
Чем помочь?

**Comment by Alexey-T** [comment]
dlg_proc для Report.

**Comment by kvichans** [comment]
что это?

**Comment by Alexey-T** [comment]
Диалог Report для посылки емейл вам

**Comment by kvichans** [comment]
Что сделать с этим диалогом?

**Comment by Alexey-T** [comment]
Сделать его на dlg_proc

**Comment by kvichans** [comment]
Не понял.
Для теста? Навсегда?

**Comment by kvichans** [comment]
Вы про этот?
![report](https://cloud.githubusercontent.com/assets/7419630/25626291/bd7b374c-2f67-11e7-9b02-5e8e85de8e2f.png)

**Comment by Alexey-T** [comment]
Я про этот диалог

**Comment by kvichans** [comment]
Я не понял ЗАЧЕМ его переделывать.
Для теста? Навсегда?

**Comment by Alexey-T** [comment]
Чтобы поправить баг с окном ФИФ
![fif](https://cloud.githubusercontent.com/assets/4154978/25628586/6ef29176-2f6f-11e7-9cc7-76df6fc1abf2.png)

**Comment by kvichans** [comment]
Не ответили на вопрос. Переделка временная или именно этот диалог нужен на dlg_proc? Чем он выделяется прочих?

**Comment by kvichans** [comment]
Почему нужна моя помощь? Это ведь ошибка Куд, разве нет

**Comment by Alexey-T** [comment]
переделка постоянная. Может ваша ош.
если поставите 'topmost':True будет ок

**Comment by kvichans** [comment]
topmost для осн.диалога ФИФ? Это же просто. Зачем менять Report?

**Comment by Alexey-T** [comment]
сначала забыл про topmost...

**Comment by kvichans** [comment]
сейчас дам версию

**Comment by kvichans** [comment]
Сделал каждому диалогу над dlg_proc topmost=T
Помогло?

**Comment by Alexey-T** [comment]
не помогло, тогда это ош. Лаза.
