### ISSUE TITLE
Beta v 1.4.01

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#141]
![find in files 1 4 01](https://cloud.githubusercontent.com/assets/7419630/26101275/33c95376-3a39-11e7-90de-84ca13883379.png)
1. Запоминается/восстанавливается положение/размер диалогов (основной, Help, Presets)
2. Заработал resize для основного диалога (высота фиксирована) и для Help. Из диалог Adjust размеры убраны.
3. Добавлена скрытая кнопка. Теперь `Alt+V` по циклу отображает/прячет контролы для `Not in file` и `Replace`
4. Кнопки переставлены (Adjust, Help) и сдвинуты (More/Less)
5. Картинка в Help изменилась
![fif-hints_820x400](https://cloud.githubusercontent.com/assets/7419630/26101528/1ee3d67e-3a3a-11e7-9ad2-bdc29e3bb7c9.PNG)
5. Запоминается последняя активная вкладка в Help

Нужно тестирование на Лин/Мак

---
Осталась проблема:
- memo в Help не меняет высоту при переключении вкладок.

**Comment by kvichans** [comment]
Off: Это Куд изменил цвет шрифта в tooltip-ах? По картинке из Help видно, что раньше был черный, а теперь серый.

**Comment by Alexey-T** [comment]
> Куд изменил цвет шрифта в tooltip-ах?

Зависит только от Лаза, не Куд

resize не активен для гл.окна (ОК для окна help).

**Comment by kvichans** [comment]
>resize не активен

Чем помочь? У меня работает

**Comment by kvichans** [comment]
@Alexey-T 
Просьба. Выложите снимки диалога в Лин и Мак.

**Comment by Alexey-T** [comment]
тут кнопки maximize нет.

![lin](https://cloud.githubusercontent.com/assets/4154978/26110198/4b7c4b42-3a5a-11e7-9b67-021e0490a56c.png)

**Comment by Alexey-T** [comment]
На Мак посмотрю вечером..

**Comment by kvichans** [comment]
Спасибо за снимок на Лин
1. В целом нормально.
2. Но верт. выравнивание режет глаза:
- Кпопки Find/Count/Browse уплыли вниз относительно комбо слева
- Подпись First - вверх от edit справа

Будете исправлять верт. выравнивание?

**Comment by Alexey-T** [comment]
Контролы стоят как вы задали x/y- как это поправить

**Comment by kvichans** [comment]
Ctrl+Adjust выведет диалог настойки для текущей платформы. Нужно в нем все выравнять и нажать Save

**Comment by Alexey-T** [comment]
Спасибо , написал багрепорт...

**Comment by kvichans** [comment]
А в чем проблема? В Лаз? Какая?
