### ISSUE TITLE
Tips help er

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#143]
Окно tips такое

![fif--](https://cloud.githubusercontent.com/assets/4154978/26103123/b3e9c552-3a40-11e7-940d-43b90b6199db.png)

**Comment by Alexey-T** [comment]
Окно по "tree" тоже.

**Comment by kvichans** [comment]
Это та проблема, про которую я написал в #141 
Решу позже

**Comment by kvichans** [comment]
На вашей картинке все checkbutton выглядят одинаково. Но один из них должен быть в состоянии нажат. Это проблема Лаз?

**Comment by Alexey-T** [comment]
checkbtn- Проверил, работают, на скрине мышь над кнопой

**Comment by Alexey-T** [comment]
Это (баг) есть в 2.х.

**Comment by kvichans** [comment]
Да, это еще не исправлено. В планах
