### ISSUE TITLE
Win scale 150%

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#145]
Контролы липнут, длг маленький. надо DLG_SCALE

![fif-150p](https://cloud.githubusercontent.com/assets/4154978/26209822/8bf48426-3bf6-11e7-9a4d-196ab8e90a6f.png)

**Comment by kvichans** [comment]
поясните

**Comment by Alexey-T** [comment]
Диалог не scaled. контролы большие (тк не мои), а координаты небольшие. контролы липнут.

**Comment by kvichans** [comment]
И? Что вы ждете от плагина такого, что нельзя сделать в ядре+cudatext.py?

**Comment by Alexey-T** [comment]
если ядро будет скейлить само, то будет проблема с точным рисованием, через canvas_proc+ type=paintbox.
И проблема с DLG_COORD_ акшенами.
