### ISSUE TITLE
Save as preset- crash

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#149]
Куд вылетает сразу (выбор save as preset), не вижу какой лог.

**Comment by kvichans** [comment]
Не повторил

**Comment by Alexey-T** [comment]
Вот конфиг- открываю длг, сразу save as preset, crash 
[cfg.zip](https://github.com/kvichans/cuda_find_in_files/files/1040553/cfg.zip)

**Comment by kvichans** [comment]
У меня с ним отрабатывает без сбоя
