### ISSUE TITLE
Nav, same group

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#15]
Запись `</home/user/lazarus/lcl/dbctrls.pp(1750)>`
- навит в строку 1751
- не скролит к каретке (есть команда "скрол к каретке")

**Comment by Alexey-T** [comment]
надо назвать "Navigate to source";
лучше отделить "Navigate*****" в Плагинс линией

**Comment by kvichans** [comment]
1) На моих примерах каретка попадала в правильную строку. Нужны подробности
2) ToDo (просто забыл)
3) rename - ok
4) separator - ok

**Comment by Alexey-T** [comment]
1) Искал файлы *.pp. по рез-ту перешел в код "navigat, same grp". и все.

**Comment by Alexey-T** [comment]
1)Искал

![ff](https://cloud.githubusercontent.com/assets/4154978/14580932/da27c2e2-03ef-11e6-93e4-e06370c16f18.png)

**Comment by kvichans** [comment]
1) не повторил
2) 3) 4) fix
