### ISSUE TITLE
Less hides not all ctr's

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#152]
![fif](https://cloud.githubusercontent.com/assets/4154978/26627341/cdd160ec-4602-11e7-9453-ea7150c5761e.png)

**Comment by Alexey-T** [comment]
"Adv ....." не скрыто.

**Comment by Alexey-T** [comment]
2) пуск в режиме LESS - потом More не показывает ничего

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
2. "не показывает ничего"? не показывает лишнего или нужного

**Comment by Alexey-T** [comment]
Вот так
![mor](https://cloud.githubusercontent.com/assets/4154978/26627638/ce203928-4603-11e7-9b40-41cdb1f2814b.png)

**Comment by kvichans** [comment]
Все отработало (спрятались лишние контролы), кроме изменения размера диалога.
Так как у меня размер меняется, подозреваю разницу в отработке
dlg_proc(id_dlg, DLG_PROP_SET, ***)
Дать репро-код?

**Comment by Alexey-T** [comment]
Да,плис

**Comment by kvichans** [comment]
Сори. Воспроизвел

**Comment by Alexey-T** [comment]
опс. я про другое. Открылся длг с кнопко More>>. жму ее. и размер поменялся. но вид == картинка выше.

**Comment by kvichans** [comment]
Да, это и повторил

**Comment by kvichans** [comment]
Исправил. Доделаю имена Пресетов и выложу на ГХ
