### ISSUE TITLE
Cannot rename preset

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#153]
поменял в диалоге

    #2: "*.pas *.inc *.pp" in "/home/user/lazarus/lcl/interfaces"

на

    а: "*.pas *.inc *.pp" in "/home/user/lazarus/lcl/interfaces"

нажал Ок. Открыл длг- имя не меняется

**Comment by kvichans** [comment]
А как диалог закрыли? Если по Cancel - то это нормально, все действия делаются на копии данных

**Comment by Alexey-T** [comment]
Нажал кн. ОК

**Comment by kvichans** [comment]
А-а-а. ToDo
