### ISSUE TITLE
fif_locale_encoding default

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#155]
... cp1251. Это в Лине. Лин разве знает про РУ кодировки. надо western.

**Comment by kvichans** [comment]
Не понял намека.
Сейчас стоит
`DEF_LOC_ENCO = 'cp1252' if sys.platform=='linux' else locale.getpreferredencoding()`

**Comment by Alexey-T** [comment]
Тут нет * значит это дефолт cp1251
![ru](https://cloud.githubusercontent.com/assets/4154978/26629738/6a6a57b6-460c-11e7-98de-5e50ed2821fa.png)
?

**Comment by kvichans** [comment]
Что у вас показывает консоль для `=sys.platform`?

**Comment by Alexey-T** [comment]
linux.

**Comment by kvichans** [comment]
Да. Понял. Когда составлял файл fif_options.json, заложил в него свои умолчания.
Еще не придумал, как разрулить

**Comment by kvichans** [comment]
Понял. Просто изменил умолчание и комментарий в fif_options.json

**Comment by kvichans** [comment]
Понял. Просто изменил умолчание и комментарий в fif_options.json
