### ISSUE TITLE
FIF, use "pages"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#156]
"type=pages" есть- это табы и к ним страницы- видна страница только
для одного таба.
Просьба- заюзать "pages" в ФИФ. в help.
Это и отладка Куд

**Comment by Alexey-T** [comment]
Счас залил тест для pages - команда в cuda_testing_dlg_proc

**Comment by kvichans** [comment]
Посмотрю

**Comment by Alexey-T** [comment]
напомню про этот пост.
