### ISSUE TITLE
Cleared input

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#157]
при нажатии More/Less пропадает мой текст из полей ввода... из поля Find what.

**Comment by kvichans** [comment]
Может быть это наведенная от ошибки #152

**Comment by kvichans** [comment]
Попробуйте с ГХ

**Comment by Alexey-T** [comment]
наведенные помехи. :))
Проверил, еще есть

**Comment by kvichans** [comment]
Да, это был мой баг, а не наведенный
