### ISSUE TITLE
Er on find in less-mode

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#158]
Менал все инпуты вверху, потом поиск, и вот
![fif---er](https://cloud.githubusercontent.com/assets/4154978/26632976/8d30472a-461a-11e7-93a3-3dc41261e904.png)

**Comment by Alexey-T** [comment]
Теперь more mode открывается с ничем
![cle](https://cloud.githubusercontent.com/assets/4154978/26633198/4961897c-461b-11e7-855b-ea975bad04c3.png)

**Comment by kvichans** [comment]
Повторил. Исправил
Значения в Adv полях вам нужно восстановить руками

**Comment by Alexey-T** [comment]
новый ГХ код.
Все равно баг
![00](https://cloud.githubusercontent.com/assets/4154978/26635678/3a38ba8a-4623-11e7-8a62-8c35e2ab9e5d.png)

**Comment by kvichans** [comment]
Я поправлю код
Вы просто задайте 0 в поле Firsts

**Comment by Alexey-T** [comment]
ok, понял, что изза firsts.
