### ISSUE TITLE
Last file mask not saved for 2nd search

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#159]
2.1.10
искал по маске - ввел ее 1й раз- *.pas *.pp *.inc *.lfm
Все нашел
Длг закрылся
Второй вызов диалога- маски в вводе нет и в истории нет :(

**Comment by kvichans** [comment]
Как диалог закрылся:
- по Close?
- по Esc?
- Сам (какое значение у опции fif_hide_if_success?)?

**Comment by Alexey-T** [comment]
Сам,   "fif_hide_if_success" : true,

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Сейчас осталась дыра. Введенные значения не сохраняются по Esc. Думаю как перехватить событие

**Comment by kvichans** [comment]
Закрыл дыру. Изменения произошли лишь в 4 строках кода :)

**Comment by Alexey-T** [comment]
Спасибо..

**Comment by Alexey-T** [comment]
Хорошо бы обновить версию

**Comment by kvichans** [comment]
Нет. Версию я обновлю не сейчас
Нужно Help-диалог исправлять - это требует времени

**Comment by Alexey-T** [comment]
вы не обижаетесь если вам говорить "Нет"?

**Comment by kvichans** [comment]
??
Сейчас публичная версия полностью совпадает по функциям с разрабатываемой. Процесс перехода на dlg_proc оказался долгим. Это нормально
