### ISSUE TITLE
Enter key 2-3 times

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#161]
Идет поиск,
плохо видно что идет,
случайно жму еще 1-2 раза enter в поле find what ---> 3 поиска

**Comment by Alexey-T** [comment]
хорошо бы запретить ввод пока не прервали поиск.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Поставил кнопки Find/Count/Replace в состояние _недоступны_
Проверьте, что стало лучше

**Comment by Alexey-T** [comment]
Да, ОК
