### ISSUE TITLE
Problem in 2.2.02

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#162]
- ищу строку, кнопки запретились
- ничего не нашло, длг остался
- правлю строку и жму enter--а кнопки запрещены и поиск не повторяется никак.

**Comment by kvichans** [comment]
Повторил

**Comment by kvichans** [comment]
Эту легко решил.
Но по дороге понял, что Фиф потерял часть своей функциональности. Теперь `Esc` попадает в диалог и закрывает форму, а не как раньше - только в 
`app_proc(PROC_SET_ESCAPE)`
`app_proc(PROC_GET_ESCAPE`
Нужно думать, как восстановить прежнюю работу.
Главная проблема - `Esc` не ловится **внутри** диалога.

**Comment by Alexey-T** [comment]
От  АПИ что-то нужно править?
Esc можно пробовать ловить в on_key_down

**Comment by kvichans** [comment]
Ничего нового не нужно. Моя внутренняя проблема
