### ISSUE TITLE
Crash on "Tags..." btn

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#164]
FIF 2.2.03
в Хелп - OptEditor - жму кнопку Tags... ==> вылетает

![fif](https://user-images.githubusercontent.com/4154978/30050687-014ddc2c-9228-11e7-8d6f-7ad013d72e1f.png)

**Comment by kvichans** [comment]
Странно, что не описали как "вылетает".

**Comment by Alexey-T** [comment]
клик - и вся Куда  (в Лин) сразу вылетела без ошибки.

**Comment by kvichans** [comment]
А как я буду это лечить? У меня работает без вылета

**Comment by kvichans** [comment]
Проблема-то в ядре

**Comment by Alexey-T** [comment]
на втором ПК можете поставить VM и в лине проверить.

**Comment by Alexey-T** [comment]
это может быть exception- в Вин он не крешит Куд а в Лин да

**Comment by kvichans** [comment]
Уже писал, что у меня нет доступа к VM.

**Comment by Alexey-T** [comment]
дать мой старый netbook на время?

**Comment by kvichans** [comment]
Как вы себе это представляете?

**Comment by Alexey-T** [comment]
да, правда, это далеко от меня.

**Comment by kvichans** [comment]
Удаленное управление?

**Comment by Alexey-T** [comment]
для удаленного упр. ПК лучше купить сервер в инете, можно virtual server. стОит где-то 5$ в месяц

**Comment by Alexey-T** [comment]
там можно в консоли скачать Куд черех "wget", распаковать итд

**Comment by kvichans** [comment]
В ядре Куд на Лин дырка. Мне она жить не мешает.
