### ISSUE TITLE
Beta 2.3.01: Many folders and project's folders

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#165]
![default](https://user-images.githubusercontent.com/7419630/30423685-5099dc74-994c-11e7-88c8-ab32c29a84f3.png)
1. В поле `In folder` теперь можно задавать несколько папок
2. В поле `In folder` теперь можно задать `<Project Folders>` (Presets в помощь)
3. В поле `In folder` теперь можно использовать домашнюю папку в виде `~` и переменные окружения в виде `$NAME` или `${NAME}`
4. В галке `Context` теперь явно отображается сколько будет строк до/после

@Alexey-T 
Потестируйте поиск в папках проекта

**Comment by Alexey-T** [comment]
Проверил на простом проекте. спасибо.
