### ISSUE TITLE
wish: Make shorter macros

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#166]
```
<Open Files> --> <Tabs>
<Project Folders> --> <Proj>
```

**Comment by kvichans** [comment]
Можно
ToDo

**Comment by Alexey-T** [comment]
а можно еще короче? `<t>, <p>`

**Comment by kvichans** [comment]
Не можно :)

**Comment by Alexey-T** [comment]
это удобно набирать руками..

**Comment by kvichans** [comment]
Но можно, если очень хочется - буду брать первые две буквы от любого ввода

**Comment by kvichans** [comment]
```
2.3.02 (2017-09-14)
added: synonyms <t>==<Tabs>==<Open Files> and <p>==<Proj>==<Project Folders>
```
Тестируем
![default](https://user-images.githubusercontent.com/7419630/30437965-a80196ba-9978-11e7-80aa-f04f4bcfb647.png)
