### ISSUE TITLE
FreeBSD error, subprocess

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#168]
(Error on both GH version and release)
![freebsd-er](https://user-images.githubusercontent.com/4154978/31305532-995d4d10-ab44-11e7-85f7-2044eeb99fb8.png)

**Comment by Alexey-T** [comment]
"import subprocess" works.

**Comment by kvichans** [comment]
Да, чистый баг - скопировал из сети код и не посмотрел, что в нем применяется.
Поправил список `import`.
