### ISSUE TITLE
New Ubuntu 17.10, big fonts

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#169]
"big fonts" gives bad FIF window.
how to fix: use DLG_SCALE.

![fif-lin](https://user-images.githubusercontent.com/4154978/31965885-684b5f70-b911-11e7-8636-ca811d72fe90.png)

**Comment by kvichans** [comment]
Насколько я помню, когда-то давно уже пытался использовать DLG_SCALE, но тогда это не помогло. Может быть сейчас будет лучше.
Подскажите по какой схеме его применять.

**Comment by Alexey-T** [comment]
я тестировал, и должен работать.  1) DLG_SCALE надо вызвать только 1 раз перед самым показом юзеру. менять потом позиции уже трудно- все увеличено,  x y w h все вместе.

метод 2)
читать текущий scale - PROC_GET_SYSTEM_PPI. и самому увеличить все x y w h.

**Comment by kvichans** [comment]
Что это за момент "перед самым показом юзеру"? Перед DLG_SHOW_MODAL?

**Comment by Alexey-T** [comment]
В смысле не перед показом, а просто ставить новые контролы потом нельзя так просто, они наложатся на зумированые контролы

**Comment by kvichans** [comment]
Добавил вызов 
`dlg_proc(id_dlg, DLG_SCALE)`
перед
`dlg_proc(id_dlg, DLG_SHOW_MODAL)`.

На моей работе это не отразилось.
Попробуйте из ГХ.

**Comment by kvichans** [comment]
Можете дать снимок? Интересно как это выглядит

**Comment by Alexey-T** [comment]
написал в момент #170. пока еще плохо. и Вин и Лин.

**Comment by kvichans** [comment]
А снимок будет?

**Comment by Alexey-T** [comment]
увы. я два раза постил но ГХ давал ошибку для пнг файла.
