### ISSUE TITLE
fold in editor

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#17]
текст не фолдится. при выводе. причина - лексер ищет блок от поз. посл. изменения. Делайте изменение 1й строки. Или делайте ed.insert('\n'.join(lines))

**Comment by kvichans** [comment]
Никак не могу сообразить каким способом мне **добавлять по одной строке в конец** документа, чтобы это работало и с пустым и с заполненным документом.
Может так `ed.insert(0, ed.get_line_count()-1, my_line+'\n')`?

**Comment by Alexey-T** [comment]
Не так, надо если get_line_count=1 и строка_0 пуста, делать не insert а "запись строки 0"

**Comment by kvichans** [comment]
Попробовал так

```
        def append_line(line, to_ed=ed):
            if to_ed.get_line_count()==1 and not to_ed.get_text_line(0):
                # Empty doc
                to_ed.set_text_line(0, line)
            else:
                to_ed.set_text_line(-1, line)
```

Заполняется. Это нормальный код?
Как теперь включить фолдинг?

**Comment by kvichans** [comment]
У меня после такого перезаполнения фолдинга нет. Но если руками вставить/убить пустую первую строку, то - есть. Что сделать чтобы сразу был?

**Comment by Alexey-T** [comment]
сделать изм-е выше начала блока.

**Comment by kvichans** [comment]
как это? Какие команды API вызывать?

**Comment by Alexey-T** [comment]
вставить строку+ удалить,
или- запись в строку 0 строки 0

**Comment by kvichans** [comment]
какими командами?

**Comment by Alexey-T** [comment]
get_text_line/ set_text_line
insert/ delete

**Comment by kvichans** [comment]
Нужны три примера кода
1. Заполнение нового пустого таба **построчно**.
2. Перезаполнение _с начала_ **построчно**
3. Дополнение _в конец_ **построчно**

чтобы фолдинг работал.
Можете дать хоть один?

**Comment by Alexey-T** [comment]
не могу. Не делал. знаю что надо  править, чтобы был фолд ниже

**Comment by kvichans** [comment]
У меня нет идей, как получить фолдинг.

**Comment by Alexey-T** [comment]
посмотрю.

**Comment by Alexey-T** [comment]
конец _report_to_tab,

```
    #hack to update folding
    s = rpt_ed.get_text_line(0)
    rpt_ed.set_text_line(0, '')
    rpt_ed.set_text_line(0, s)
```

fixed

**Comment by kvichans** [comment]
Ура, работает!
Надеюсь хак временный
