### ISSUE TITLE
Version 2.3.05 Bagfix

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#174]
Исправлен серьезный баг. 
- Если задать несколько исходных папок в поле `In folder`.
- Если задать ограничение на обход в поле `In subfolders`.
- То при достижении ограничения в одной из заданных папок, следующие за ней не просматривались.

Например, при установке `In folder only`, поиск файлов происходил только в первой из папок.

**Comment by Alexey-T** [comment]
Спасибо
