### ISSUE TITLE
Config presets dialog- right part is disabled always

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#175]
Screen
![fif-enabl](https://user-images.githubusercontent.com/4154978/33717804-4dd29bd6-db6c-11e7-83e9-610512f54bad.png)

**Comment by kvichans** [comment]
Да, это было сознательно сделано из-за дефекта АПИ.
Позже буду заново проверять есть ли дефект.

**Comment by Alexey-T** [comment]
решено?

**Comment by kvichans** [comment]
ToDo
