### ISSUE TITLE
Clean install-- lexer "Search results" not used

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#177]
- Clean Cud 1.40.1 install, 
- clean FIF install (release).

after search, (none) lexer active for found results.
must be: "Search results" lexer.

**Comment by kvichans** [comment]
Todo

**Comment by kvichans** [comment]
1. Я смогу при запуске ФИФ скопировать файлы
`Search results.lcf`
`Search results.cuda-lexmap`
в папку `data\lexlib`.
2. Как эти файлы подхватить в Куд? 
Понятно, что перезапуска достаточно. Но это не удобное решение.
Можно ли _оживить_ лексер через АПИ?

**Comment by Alexey-T** [comment]
https://github.com/Alexey-T/CudaText/blob/master/app/data/lexlib/Search%20results.lcf
Лекс уже в Куде. зачем вы его копируете? ed.set_prop(PROP_LEXER_FILE, ...)

**Comment by kvichans** [comment]
Поясните смысл первого поста

**Comment by kvichans** [comment]
Может быть речь о 
- Чистая установка Куд
- Новая установка Фиф
- Первый поиск
- Результаты без лексера

Не повторил
![default](https://user-images.githubusercontent.com/7419630/36087785-266adcb8-0fe5-11e8-9672-9954693eaa39.png)

**Comment by Alexey-T** [comment]
Вы правы. речб про это. но у меня в рез-татах нет лексера.
Может ФИФ у вас не релиз?

**Comment by kvichans** [comment]
На картинке - после установки Фиф из plug-man

**Comment by Alexey-T** [comment]
не повторил на 2м ПК.
