### ISSUE TITLE
Indent in rpt

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#179]
Можно делать индент по 2 пробела? а не "1 таб". в отчете. 1 таб= 8 пр =длинно

**Comment by kvichans** [comment]
Я себе сразу сделал "таб длинной 1 пробел" в `lexer FiF.json`
`  "tab_size": 1,`
Отображается так
![default](https://user-images.githubusercontent.com/7419630/36465472-36638ee6-16e6-11e8-9ad1-ffc1707d4d9f.png)
Удобно. 

Вы ходите поменять "для всех". Какие варианты реализации?

**Comment by Alexey-T** [comment]
ed1.set_prop(PROP_TAB_SIZE, 2)
или делать индент пробелом.
Черех lexer override менять юзерам трудно

**Comment by kvichans** [comment]
`ed.set_prop(PROP_TAB_SIZE, 2)` - это жестоко. Пользователь лишается возможности сделать свою настройку.
Какие еще варианты?
Почему бы из плага _при первом вызове_ не сформировать lexer override?

**Comment by Alexey-T** [comment]
Оверрайдом трудно пользоваться обычному юзеру

**Comment by kvichans** [comment]
"трудно" = не хватает инструментов.
Нужно в OptionEditor добавить управление overrided - тогда пользователь не будет его боятся.

**Comment by Alexey-T** [comment]
Сначала наверно переписать на dlg_proc

**Comment by kvichans** [comment]
Да, конечно - там нужно много что переписать.

**Comment by kvichans** [comment]
Вот теперь как раз и можно подумать об автоматическом overrided при первом вызове.
Плагин может проверить, что в `lexer Search results.json` нет опции `tab_size` и выставить ей значение 2.
Делать?

**Comment by Alexey-T** [comment]
делать.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Можно тестировать из ГХ.
Добавлена опция `fif_lexer_auto_tab_size` с умолчанием `2`.
![default](https://user-images.githubusercontent.com/7419630/40301920-3ddc0558-5cf6-11e8-93f0-b4e4633a3d61.png)
Любое значение отличное от `0` будет **один раз** устанавливать для лексера отчета `tab_size` в это значение.

**Comment by Alexey-T** [comment]
тогда можно сделать булево значение.

**Comment by Alexey-T** [comment]
да- имеет смысл целое значение. Ок

**Comment by Alexey-T** [comment]
GH version 2.2.03
по поиску слова tab- нет опций. ??

**Comment by kvichans** [comment]
Вы про что? Версия чего? Покажите где ищете

**Comment by kvichans** [comment]
Видимо вы не обратили внимание, что на снимке Настройки ФИФ

**Comment by Alexey-T** [comment]
версия плагина ФИФ, из гх, и в ней в диалоге опций нет опций со словом выше.

**Comment by kvichans** [comment]
А-а-а. Мой косяк - определение опций забыл выложить

**Comment by kvichans** [comment]
Done
