### ISSUE TITLE
OS scaled

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#181]
@Alexey-T 
Кажется придумал, как скалировать высоту `label`, `button`, `checkbutton`.
Выложил в ГХ. 
Мне самому больше не хочется повторять перенастройку ОС - тяжелые последствия. Проверьте вы: получилось?
Может быть еще какие-то контролы остались _низкими_?

Если не сложно, дайте снимки основного диалога и Help в _растянутой_ ОС.

**Comment by Alexey-T** [comment]
мне надо будет загружать второй ПК в вин. посмотрю позже..

**Comment by Alexey-T** [comment]
Теперь нормально смотрится
только один снимок при 125%
![fif](https://user-images.githubusercontent.com/4154978/36550120-880d0c3e-1805-11e8-9755-d28f2d240076.png)

**Comment by kvichans** [comment]
Снимок Help сможете дать?

**Comment by Alexey-T** [comment]
![fif](https://user-images.githubusercontent.com/4154978/36550483-74299222-1806-11e8-937c-c3544b11db09.png)

**Comment by kvichans** [comment]
Вроде не плохо. Картинку растягивать - только портить.

**Comment by Alexey-T** [comment]
может, картинку поменяете на новый вид?

**Comment by kvichans** [comment]
Картинку полностью переделаю

**Comment by Alexey-T** [comment]
close?
