### ISSUE TITLE
Beta 2.3.08. Redesign

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#182]
![default](https://user-images.githubusercontent.com/7419630/36537590-b1d8bbf4-17e1-11e8-80d6-6b696621e262.png)

![default](https://user-images.githubusercontent.com/7419630/36537387-05d67576-17e1-11e8-8572-76499b828de1.png)

Изменения в компоновке
1. Удалена кнопка Close
2. Кнопка Help встала на ее место. Теперь она видна всегда.
3. Кнопка Adjust передвинута на ----, чтобы это показывало ее назначение
4. Группы контролов под ----- подвинуты, чтобы заполнить низ диалога

@Alexey-T 
1. Как это выглядит на Лин и в Мак?
2. Adjust сейчас управляет только отображением 
![default](https://user-images.githubusercontent.com/7419630/36537997-eeb83760-17e2-11e8-92ba-bfbf89df0b80.png)
Может ей имя поменять? Можете что-то предложить?

**Comment by Alexey-T** [comment]
"Adjust"- OK имя. можно еще Layout.

**Comment by Alexey-T** [comment]
![fi](https://user-images.githubusercontent.com/4154978/36539725-cffc3b0e-17e8-11e8-8d03-ed555551e224.png)

**Comment by kvichans** [comment]
Это, видимо, в Лин

**Comment by kvichans** [comment]
Про Adjust. Лучшее имя - нет имени. Будет так
![default](https://user-images.githubusercontent.com/7419630/36550462-67df78ba-1806-11e8-8511-41aebb25fdb8.png)
