### ISSUE TITLE
Вета 2.3.09 - new help-picture, repro-by-option

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#184]
1. Кнопка `...` теперь появляется только при отображении всех контролов
![default](https://user-images.githubusercontent.com/7419630/37281910-a361457a-2603-11e8-88bf-53ec4f31b78d.png)
![default](https://user-images.githubusercontent.com/7419630/37281859-814cfd26-2603-11e8-8566-a44cc5f06c7f.png)

2. Пересоздана картинка в диалоге Help. Попробовал [draw.io](https://www.draw.io/), оказался удобный векторный редактор.
![default](https://user-images.githubusercontent.com/7419630/37281270-8ab4b414-2601-11e8-92a8-db94c57a5d6f.png)

3. Появилась опция для создания чистого репро-кода.
Если в `user.json` добавить `fif_repro_to_file":"repro_dlg_fif.py",` то 
- В файле с указанным именем (в TEMP-папке OC, например, `c:\t`) 
- будет сформирован набор АПИ-вызовов, 
- в консоли появится сообщение
`...  exec(open(r"c:\t\repro_dlg_fif.py", encoding="UTF-8").read())`
- Если эту строку запустить, то отобразится диалог
- Файл будет обновляться при каждом вызове ФИФ

@Alexey-T Проверьте, плз, работу репро-опции

**Comment by Alexey-T** [comment]
Прописал опцию. скопировал строку, `exec(open(r"/tmp/repro_dlg_fif.py", encoding="UTF-8").read())` . запустил. это вызовато ФИФ с пустым полем ввода. непонятно зачем это.

**Comment by kvichans** [comment]
Спасибо. Значит работает
Это позволяет повторить _наполнение_, но не _функционировние_. Реакцию на действия пользователя можно туда добавлять, когда это потребуется.

**Comment by Alexey-T** [comment]
можно закрыть многие Beta issue от вас?
