### ISSUE TITLE
Вета 2.3.10: Context menus

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#185]
У многих элементов появились контекстные меню
![default](https://user-images.githubusercontent.com/7419630/37365182-d1355a8a-270d-11e8-838a-ae123315464d.png)
![default](https://user-images.githubusercontent.com/7419630/37365196-dc4e0c46-270d-11e8-9762-84f10c49be44.png)
![default](https://user-images.githubusercontent.com/7419630/37365216-e9668b4c-270d-11e8-936a-17e38a9af974.png)
![default](https://user-images.githubusercontent.com/7419630/37365229-f3c53f0c-270d-11e8-9e10-2304dc24b629.png)
![default](https://user-images.githubusercontent.com/7419630/37365260-05394206-270e-11e8-8c6f-05a3a96e68f3.png)
![default](https://user-images.githubusercontent.com/7419630/37365269-0f808332-270e-11e8-8933-8776663837a0.png)
![default](https://user-images.githubusercontent.com/7419630/37365288-1b38f6aa-270e-11e8-9f47-1bf3171ec07b.png)

Кроме этого реакция на `...` (`Alt+.`) теперь показывает не диалог, а локальное меню
![default](https://user-images.githubusercontent.com/7419630/37365380-6312971a-270e-11e8-942b-ea2009fd4788.png)

**Comment by Alexey-T** [comment]
Смотрится хорошо.

**Comment by Alexey-T** [comment]
Меню работают.

**Comment by kvichans** [comment]
Спасибо

**Comment by Alexey-T** [comment]
можно закрыть старые аннонсы ФИФ.
