### ISSUE TITLE
MsgBox - make over FIF

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#186]
Нажимаю count при пустом после what. Msgbox -надо показать поверх FIF. Пока он вместо FIF.

**Comment by kvichans** [comment]
Не понял проблему
У меня так
![default](https://user-images.githubusercontent.com/7419630/37425345-150ee0b6-27d4-11e8-8d6c-9b7ed7f435ae.png)

**Comment by Alexey-T** [comment]
А, это окно Фиф идёт на задний план, глюк Лаз
