### ISSUE TITLE
wish: put 2 menuitems to Options/ Settings-plugins

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#188]
to do it, set in install.inf menu= parameter for menu items. Example- plugins ProjManager, TabsList.

-Config navigation
-View-edit options

**Comment by kvichans** [comment]
Уже есть
![default](https://user-images.githubusercontent.com/7419630/37708768-efb5ef0e-2d18-11e8-8ce3-79af7d5a5588.png)

**Comment by Alexey-T** [comment]
виш это то что надо переместить эти два пункта в Options/plug-ins. как у моего плагина ProjManager.

**Comment by Alexey-T** [comment]
точнее сдублировать там.

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
пока в Settings-plugins пунктов нет.

**Comment by kvichans** [comment]
Напомните, что для этого нужно сделать

**Comment by Alexey-T** [comment]
.inf - [itemNNN] может иметь ключ menu= - одно из значений дублирует п-т в settings-plugins, другое перемещает туда.

**Comment by Alexey-T** [comment]
в Вики описано..

**Comment by kvichans** [comment]
Те два пп уже должны работать:
![default](https://user-images.githubusercontent.com/7419630/40230716-4f250e2e-5aa1-11e8-9ddc-4894f2556d9d.png)

**Comment by Alexey-T** [comment]
в релизе 2.3.13 - этого нету

**Comment by kvichans** [comment]
Нда, сори. Забыл опубликовать install.inf

**Comment by Alexey-T** [comment]
надо обновить + версию в регистри.

**Comment by kvichans** [comment]
Done
