### ISSUE TITLE
deprecated "props" prop

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#189]
дал в консоль строку. на ФИФ полезло-

Python 3.5.3
Init: cuda_tabs_list
Loading session: history session.json
Init: cuda_project_man
Startup: total: 736ms, including plugins: 14ms
Init: cuda_find_in_files
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "colorpanel"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "label"
Deprecated API: dlg_proc "props" for "button"

**Comment by kvichans** [comment]
Это вы зря. Нельзя удалять этот `prop`. Пусть будет как альтернативный способ задания **вместе** с `ex*`.
Его преимущество в **компактности**.
А у `ex*` нет преимущества в _прозрачности_! Что означает `ex4`?

**Comment by Alexey-T** [comment]
ok.
