### ISSUE TITLE
use control "editor"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#190]
Контрол для показа json config в хелпе. очень хочется чтобы было.

**Comment by kvichans** [comment]
Чем это лучше OptEd?
В json будут только значения. Не будут видны комментарии и варианты значений.

**Comment by kvichans** [comment]
На контрол `editor` я посматриваю с другой стороны.
Может быть сделать вывод результатов в него?.. Есть над чем подумать

**Comment by Alexey-T** [comment]
не понимаю вас. при чем тут OptEd. это лучше чем "memo".  json будет красивый.

json который выводится по кнопке Opts в хелпе.

**Comment by kvichans** [comment]
А-а-а. Я подумал, что хотите **менять** опции.
Да, раскраска и readonly - к месту.
ToDo

**Comment by kvichans** [comment]
Что-то уже получается
![default](https://user-images.githubusercontent.com/7419630/37777570-f4114504-2df8-11e8-9d7c-3ee5b957487f.png)
Как убрать последнюю вертикальную линию? Остальные GUTTER уже спрятал

**Comment by Alexey-T** [comment]
будет в апдейте- Prop_gutter_all, Prop_gutter_states.

**Comment by kvichans** [comment]
жду

**Comment by kvichans** [comment]
Как мне задать рамку для editor?
![default](https://user-images.githubusercontent.com/7419630/37787104-4a76e9c4-2e0f-11e8-8472-c1a2c6011833.png)

**Comment by Alexey-T** [comment]
пример

dlg_custom('',400,400,'type=editor\1pos=10,10,200,200\1border=1')

**Comment by kvichans** [comment]
Помогло
![default](https://user-images.githubusercontent.com/7419630/37787936-3e335218-2e11-11e8-9df0-1d28a9fef3b5.png)

**Comment by kvichans** [comment]
Проблема только в вики: `border` не задокументирован

**Comment by Alexey-T** [comment]
в разделе control properties...

**Comment by kvichans** [comment]
Еще раз проверил - не нашел. По слову border вижу только exN

**Comment by kvichans** [comment]
Нашел :)

**Comment by Alexey-T** [comment]
Баг поиска?

**Comment by kvichans** [comment]
Стало хорошо
![default](https://user-images.githubusercontent.com/7419630/37816750-41d6ffea-2e85-11e8-9174-8c0aba7c2a4d.png)

**Comment by kvichans** [comment]
После релиза Куд выложу новый ФИФ

**Comment by kvichans** [comment]
Проблема!
![default](https://user-images.githubusercontent.com/7419630/37817262-4d12042a-2e87-11e8-91a1-24f4519b7c86.png)
1. Вывожу в консоль текст, который нужно отобразить
2. Это текст заканчивается `"fif_read_head_size(bytes)":1024,`
3. Этот же текст передаю в Editor
4. В контроле нет последней строки

**Comment by kvichans** [comment]
Передать код ФИФ?

**Comment by Alexey-T** [comment]
если можно, дайте репро код. А пока можете приписать EOL.

**Comment by kvichans** [comment]
Да, если заменить
oed.set_text_all(OPTS_JSON)
на 
oed.set_text_all(OPTS_JSON+'\n')
то отображается все строки.
Конечно, это баг

**Comment by Alexey-T** [comment]
не сделаете репро код, плиз?

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
```python
_OPTS_JSON  = r'''
//Extra options for "user.json" (needed restart after changing).
    
    // Size of buffer (at file start) to detect binary files
    "fif_read_head_size(bytes)":1024,
'''

idd=dlg_proc(0, DLG_CREATE)

idc=dlg_proc(idd, DLG_CTL_ADD,"editor")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'name':'edtr'
,'x':5, 'y':5, 'w':740, 'h':482, 'cap':''
,'val':''
,'border': '1'})

oed = Editor(dlg_proc(idd, DLG_CTL_HANDLE, name='edtr'))
oed.set_prop(PROP_RO            , True)
oed.set_prop(PROP_GUTTER_ALL    , False)
oed.set_prop(PROP_LEXER_FILE    , 'JSON')
OPTS_JSON   =_OPTS_JSON.strip()
oed.set_text_all(OPTS_JSON)


dlg_proc(idd, DLG_PROP_SET, prop={'x':690, 'y':186, 'w':750, 'h':520, 'cap':'Help'})

dlg_proc(idd, DLG_SHOW_MODAL)
dlg_proc(idd, DLG_FREE)
```

**Comment by Alexey-T** [comment]
смешно... Вы ставите prop_ro. одно АПИ это обходит. а другое нет. и теряется часть. ставить ro надо после.

**Comment by Alexey-T** [comment]
теперь set_text_all() не будет работать в readonly.

**Comment by kvichans** [comment]
@Какое отношение RO имеет к API? Это ограничение для пользователя, для GUI

**Comment by kvichans** [comment]
Это вы _смешно_ рассуждаете
Плагин на уровне API всегда может снять RO, заменить текст, поставить RO

**Comment by Alexey-T** [comment]
вобщем, ставить текст в редакторе надо с ВЫКЛ RO.

**Comment by kvichans** [comment]
Если у set_text_all() будет в вики пометка про RO, буду соблюдать протокол. То есть 
- снимать RO
- заменять текст
- ставить RO

И что ВАМ мешает избавить меня и остальных авторов от этой мороки?

**Comment by kvichans** [comment]
Согласны, что **частичная** замена текста - это очевидный баг?

**Comment by Alexey-T** [comment]
согласен. чтобы обойти это, напишу в вики про RO+set_text_all.

**Comment by kvichans** [comment]
Вы не согласны, что ограничения для пользователя нужно игнорировать при вызовах АПИ?
Получилась заплатка из-за смешивания слоев

**Comment by Alexey-T** [comment]
не знаю даже.
