### ISSUE TITLE
Small wish

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#191]
for "editor" control: turn off

ed.set_prop():
prop_minimap
prop_micromap
prop_margin (set 2000)
prop_last_line_on_top

**Comment by kvichans** [comment]
Это всегда придется делать или вы для контрола **потом** сами будете ставить?

**Comment by Alexey-T** [comment]
всегда, т.к. по умолчанию ставятся настройки от главного редактора.

**Comment by kvichans** [comment]
Бардак!

**Comment by kvichans** [comment]
Чем PROP_LAST_LINE_ON_TOP помешал?

**Comment by kvichans** [comment]
Про "бардак". Нужно ввести два умолчания: для *осн.редактора* и для *контрола*. Явно прописать это в вики.

**Comment by Alexey-T** [comment]
то что умолч. берутся от главного- это не бардак. это ОК. "нужно ввести"- не уверен. и потом это целый wish.

**Comment by Alexey-T** [comment]
опции выключены для редактора? если минимап показан в Куд- в плагине надо прятать. итд

**Comment by kvichans** [comment]
Вроде все учел?:
```python
    oed.set_prop(app.PROP_RO                , True)
    oed.set_prop(app.PROP_GUTTER_ALL        , False)
    oed.set_prop(app.PROP_MINIMAP           , False)
    oed.set_prop(app.PROP_MICROMAP          , False)
    oed.set_prop(app.PROP_LAST_LINE_ON_TOP  , False)
    oed.set_prop(app.PROP_MARGIN            , 2000)
    oed.set_prop(app.PROP_LEXER_FILE        , 'JSON')
```

**Comment by Alexey-T** [comment]
да- спс.
