### ISSUE TITLE
Call new dlg OpEd

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#192]
Если установлена последняя версия диалога Опции, то вызывается она
![default](https://user-images.githubusercontent.com/7419630/39577922-5b9acf34-4eeb-11e8-85e8-2714d25af470.png)

Прошу помощи в тестировании из ГХ

**Comment by Alexey-T** [comment]
close?

**Comment by kvichans** [comment]
Почему у меня спрашиваете? Уже протестировали на разных ОС?

**Comment by Alexey-T** [comment]
да- работает.
