### ISSUE TITLE
Opts desc text

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#193]
If True then one ESC stop all stages.
If False - only current stage.

=>
Allows Esc key to stop all stages of current search. If false - Esc stops only current stage.

**Comment by Alexey-T** [comment]
Save report after filling if tab has filename
=>
If report editor tab has a filename, save report after filling it

**Comment by Alexey-T** [comment]
Skip too big files (0 - don't skip)
=>
If value>0, skip all files, which sizes are bigger than this value (in Kb)

**Comment by Alexey-T** [comment]
Permit to log for all parts
=>
Allows logging for all search stages

**Comment by Alexey-T** [comment]
Log searching part => Allows logging for searching stage
Log reporting part => Allows logging for reporting stage
Log navigation part => Allows logging for navigation stage

**Comment by Alexey-T** [comment]
Log to file (if not empty)
=>
Sets filename of log file

**Comment by Alexey-T** [comment]
Need to log about failed reading
=>
Allows logging about failed file reads (encoding errors)

**Comment by kvichans** [comment]
Спасибо
