### ISSUE TITLE
Ver 2.3.15

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#194]
Опубликована версия 2.3.15
1. Из диалога Help удалены опции.
2. Переработано *гамбургер-меню*. Из него теперь вызываются настройки опций
![default](https://user-images.githubusercontent.com/7419630/40353861-30c67e1e-5dbb-11e8-9b14-90edabd39b17.png)
3. Мелкие исправления раскладки и подписей

**Comment by Alexey-T** [comment]
typo: "endgine"->"engine"

**Comment by Alexey-T** [comment]
нет категории у пункта-
![screenshot from 2018-05-22 12-39-39](https://user-images.githubusercontent.com/4154978/40354745-3fe2c39c-5dbd-11e8-8270-5d976864191a.png)

**Comment by Alexey-T** [comment]
поправка к хистори-
```
2.3.15 (2018-05-22)
added: New option "fif_lexer_auto_tab_size" (def=2) to auto-set tab_size for report lexer, if no such setting.
added: Allow to call Option Editor from menu "=".
added: Allow to call from "=" menu dialog to configure double-clicks in report.
changed: Hidden options from Help dialog. 
```

**Comment by kvichans** [comment]
typo - ок
Секция не является обязательной
хистори - ок

**Comment by Alexey-T** [comment]
(typo было в 2х местах- в = и в settings-plugins)

**Comment by kvichans** [comment]
исправил в двух
выложил в СФ
на ГХ появится позже

**Comment by Alexey-T** [comment]
хистори не обновили?

**Comment by kvichans** [comment]
да
