### ISSUE TITLE
Show "Configure presets..." menu item

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#196]
показать этот пункт в подменю Presets- т.к. когда режим  <<Less то кнопки Presets... нет.

**Comment by kvichans** [comment]
Уже
1. ![default](https://user-images.githubusercontent.com/7419630/40988511-f2e61962-68f3-11e8-976c-42ba2d776b80.png)


2. ![default](https://user-images.githubusercontent.com/7419630/40988403-9faf54f2-68f3-11e8-9d4a-c41512a572ec.png)
