### ISSUE TITLE
Pre-Beta with editors

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#197]
Нужно проверить базовую функциональность: компоновку и заполнение редакторов.
План проверки
1. Отключить галку `Send to` и перевызвать диалог (от перевызова потом избавлю)
![default](https://user-images.githubusercontent.com/7419630/41047684-cb9f69ea-69b5-11e8-9d9e-36f7661d22cf.png)
2. Протестировать компоновку: ресайз всего диалог и перемещение сплитера, сохранение их положений при перевызовах диалога. Спрятать лишнее (`Alt+E`)
3. Выполнить обычный поиск. Должен заполниться левый редактор "Результаты"
4. `Ctrl+Enter` должен перемещать фокус в "Результаты"
5. Перемещение каретки внутри "Результатов" должно заполнять и позиционировать левый редактор "Исходник"
![default](https://user-images.githubusercontent.com/7419630/41048187-ddf47a62-69b6-11e8-803e-381140139080.png)

**Comment by Alexey-T** [comment]
а- Gutter folding bar  пропал у левого редактора.
б- глюки с пустым местом где расширеные контролы- были при 1м вызове. потом может поправилось и история помогает. проверьте без конфига

**Comment by Alexey-T** [comment]
б- ето было при нажатиях more..less.

**Comment by kvichans** [comment]
- "Глюки" знаю - поэтому просил перевызвать после снятия галки
- Gutter folding bar нужен в Результах? добавлю

**Comment by Alexey-T** [comment]
теперь я вас не пойму. зачем просите тест недоделанного.

**Comment by kvichans** [comment]
Просьба была только про "базовую функциональность" 
Если размеры меняются, редакторы заполняются, то тестирование можно не продолжать

**Comment by Alexey-T** [comment]
да, работает. Идея едиторов сбоку плоха, мне на ноут не хватает ширины и слева и справа

**Comment by kvichans** [comment]
Хорошо - перекомпоную

**Comment by kvichans** [comment]
Поставил для "Результаты"
```python
        self.rslt.set_prop(app.PROP_GUTTER_ALL          , True)
        self.rslt.set_prop(app.PROP_GUTTER_NUM          , False)
        self.rslt.set_prop(app.PROP_GUTTER_STATES       , False)
        self.rslt.set_prop(app.PROP_GUTTER_FOLD         , True)
        self.rslt.set_prop(app.PROP_GUTTER_BM           , False)
```
Место под фолд-колонку появилось, но +/-/скрепки отображаются только при наведении мыши. Это нормально?

**Comment by Alexey-T** [comment]
нужно сделать новое АПИ set_prop для такой опции Куд. когда скрепки пропадают

**Comment by kvichans** [comment]
Зачем делать новое АПИ? Мне нравиться, что +/-/скрепки не видны, пока мышку не наведешь. Только если это чему-то еще мешает - то "нужно"
