### ISSUE TITLE
controls partly visible

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#204]
![screenshot from 2018-07-06 15-48-34](https://user-images.githubusercontent.com/4154978/42379676-2ede720e-8134-11e8-8dba-576c952e05f4.png)

**Comment by kvichans** [comment]
Это воспроизводится при следующем запуске ФИФ? 
Или наблюдается только при переключении `[ ]Send`?

**Comment by Alexey-T** [comment]
1- да
2- переключить send не могу, не вижу

**Comment by kvichans** [comment]
1. :(
2. Alt+D

**Comment by Alexey-T** [comment]
Alt+d расширяет окно и контролы так  же скрыты
обратно- тоже скрыты

**Comment by kvichans** [comment]
дайте снимок после расширения

**Comment by Alexey-T** [comment]
![screenshot from 2018-07-06 18-27-37](https://user-images.githubusercontent.com/4154978/42387280-7de95f88-814a-11e8-8c7b-e36e4ccff145.png)

**Comment by kvichans** [comment]
уже яснее

**Comment by kvichans** [comment]
Еще не понял. Сделать костыль - увеличил зазор над редакторами.
Возьмите из ГХ. Что в консоли после запуска?

**Comment by Alexey-T** [comment]
![n2](https://user-images.githubusercontent.com/4154978/42392689-528d579c-815c-11e8-8ed6-e29cb0a62a35.png)
