### ISSUE TITLE
Ignore more dirs (default)

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#205]
history:
+ Now by default, plugin ignores folders .svn / .git / .hg
(сделать игнор 3 папок)

**Comment by kvichans** [comment]
Готов сделать опцию "Добавлять к исключенным папкам паречисленные" и по умолчанию заполнить ее как вы написали. ОК?

**Comment by Alexey-T** [comment]
OK

**Comment by kvichans** [comment]
Есть сомнение, что достаточно будет описанного мной выше.
Давайте посмотрим, как сделать реальные поиски "без `.git`". Подозреваю, что нужно отбрасывать папку `.git` не только в том месте, где стартует поиск, но и во всех ниже лежащих подпапках. Так?
Если "так", то такого поведения еще нет.

**Comment by kvichans** [comment]
Добавил новую опцию
![opt](https://user-images.githubusercontent.com/7419630/42747526-6ac8cc70-88e5-11e8-8ccf-b2a6f23bebb8.png)

Значение новой опции отображается в тултипе к исключенным файлам
![default](https://user-images.githubusercontent.com/7419630/42747814-8ddae09e-88e6-11e8-96db-14a79b024b5e.png)
