### ISSUE TITLE
Idea from Atom search results

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#213]
http://blog.atom.io/2018/06/21/atom-1-28.html

Там у них часть про улучшение find results с двумя скринами,
вроде прямо в резалтс они подсвечивают все вхождения строки

**Comment by kvichans** [comment]
Посмотрю. Но у меня уже сейчас помечаются в Результах все найденные фрагменты. Небольшая тонкость только в том, что в зависимости от выбранного типа *дерева* фрагменты из одной исходной строки могут оказаться в нескольких строках Результатов

**Comment by kvichans** [comment]
Посмотрел. Там совсем про другое. Если выдавать Результаты с Контекстом (окружающие строки), то *можно* съэкономить, если пропускать повторяющиеся контексты.
