### ISSUE TITLE
Cannot find Help about <p> <t>

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#214]
не нашел в хелп длг про сокращатели `<p> <t>` и тд. Там есть?

**Comment by kvichans** [comment]
Спасибо за внимательность.
Раньше было, но выпало при переделке Help. Осталось только в тултипах
![default](https://user-images.githubusercontent.com/7419630/44191481-54549200-a134-11e8-9e4c-6709ce4dd0a8.png)

ToDo
