### ISSUE TITLE
MacOS: hotkeys Ctrl+C...

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#216]
on Mac apps don't have Ctrl+C/Ctrl+V to copy/paste, but Cmd+C/Cmd+V (ie Meta key)
so pls fix your hotkeys for Mac. all "Ctrl" repl to "Meta". (Ctrl+C Ctrl+N ...)

**Comment by kvichans** [comment]
Почему это нужно делать мне?
1. Что возвращает `app_proc(PROC_GET_KEYSTATE, '')`, когда пользователь Мака жмет `Meta+C`. Вики ничего про Мак не сообщает
`String has "c" for Ctrl pressed, "a" for Alt, "s" for Shift, "m" for Meta (Windows key)`
2. Что в параметре `data` при перехвате `on_key_down` при `Meta+C` на Мак?
3. Ядро может взять на себя переименование `Ctrl+Q` в `Meta+Q` при вызове 
`menu_proc(mid, MENU_SET_HOTKEY, command='Ctrl+Q')`

**Comment by Alexey-T** [comment]
1. когда юзер жмет Cmd+C == Мета+С, keystate has "m"
2. тоже
3. не может- т к хоткей Ctrl+Q тоже хоткей, только в мак не принято такие в прогах иметь

**Comment by Alexey-T** [comment]
(почти все проги имеют Cmd+Q hotkeys, в том числе для copy-paste)

**Comment by kvichans** [comment]
Фраза из вики `"m" for Meta (Windows key)` вводит в заблуждение?

**Comment by kvichans** [comment]
> Ctrl+Q тоже хоткей, только в мак не принято такие в прогах иметь

"не принято" или "не возможно"? Мак пользователи могу вызывать оба хоткея `Ctrl+Q` и `Meta+Q`?

**Comment by Alexey-T** [comment]
не принято. возможно. Ctrl+Q работать будет наверно

**Comment by kvichans** [comment]
Опишите в вики правила - я переделаю.
Нужно прояснить
- что содержит data в Мак
- как правильно задавать хоткеи в Мак

**Comment by Alexey-T** [comment]
- data будет как в вин при нажатии  Win+x - т.е. "m" (Meta/Windows key)
- задавать как "Meta+Q"

**Comment by kvichans** [comment]
Нужен точный ответ для "Может ли на Мак работать хоткей Ctrl+Meta+Q?"

**Comment by kvichans** [comment]
Еще поясните. Если Мак виртуальный, клава для Вин, пользователь жмет Ctrl+Q - что придет в data?

**Comment by Alexey-T** [comment]
Вы потом сами попробуете?

**Comment by kvichans** [comment]
Ждем до конца недели

**Comment by Alexey-T** [comment]
все в теме непонятно. сами попробуете?

**Comment by kvichans** [comment]
ToDo: поменяю все хоткеи с Ctrl+... на Meta+... для Мака
Только это относится не к ФиФ, а ко всем плагам - у них много назначено.

**Comment by Alexey-T** [comment]
я это и хотел. а вы все спрашивали что-то.

**Comment by Alexey-T** [comment]
решено?

**Comment by kvichans** [comment]
опубликую и потом закрою
