### ISSUE TITLE
must unfold target pos, when dbl-clicking report line

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#217]
в файле было все folded.
прыжок из ФИФ дал прыжок в строку8. но оно же фолдед.
каретки нет.
вот -
![screenshot from 2018-08-31 13-19-46](https://user-images.githubusercontent.com/4154978/44907492-c0341e80-ad20-11e8-9116-b92c81c47f91.png)

**Comment by kvichans** [comment]
нужны подробности из предыстории

**Comment by Alexey-T** [comment]
- открыли Пи файл, сделали fold all (from gutter)
- ФИФ
- в нем "поиск в текущей папке в *.py
- нашло в том же файле

**Comment by kvichans** [comment]
Какой план для диагностики и исправления?

**Comment by Alexey-T** [comment]
http://wiki.freepascal.org/CudaText_API#folding
дает воз-ть сделать unfold

**Comment by kvichans** [comment]
Это лечение (еще не все понятно)
А как узнать что строка скрыта?

**Comment by Alexey-T** [comment]
если она попала хотя бы в 1 свернутый fold range.

**Comment by kvichans** [comment]
ToDo
