### ISSUE TITLE
age UI

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#219]
age: control no.2 is empty (it must have year/mon/days?)
dropdown list empty.

**Comment by Alexey-T** [comment]
"Encoding" list is empty too here.

**Comment by kvichans** [comment]
Это последствия бага `Alt+A` - попортились имена ключей. Хорошо еще, что ясно, какие это были ключи - `items`, легко исправить.

**Comment by kvichans** [comment]
Опубликовал в СФ без смены версии
