### ISSUE TITLE
option for Age

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#221]
wish: option-3 for age: ">=" or "<=" , ie "older or equal" or "newer or equal".

**Comment by kvichans** [comment]
Уже сейчас реализовано: "<" отрабатывает как "<="

**Comment by Alexey-T** [comment]
в хелпе это описано наверно?

**Comment by kvichans** [comment]
Ой, а про Справку-то я забыл. ToDo
