### ISSUE TITLE
write help text about Age

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#222]
subj

**Comment by kvichans** [comment]
Добавил в Help 
![image](https://user-images.githubusercontent.com/7419630/57980102-6949b300-7a2f-11e9-8e60-f96f86566f4a.png)

Это копии текстов из хинтов
![image](https://user-images.githubusercontent.com/7419630/57980142-b4fc5c80-7a2f-11e9-8f13-a34bf93bf736.png)
![image](https://user-images.githubusercontent.com/7419630/57980146-c6456900-7a2f-11e9-9f32-02e2461451b0.png)
