### ISSUE TITLE
not correct "Wrap" option 

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#225]
must handle "w" option even for string "= object", to not give "= Objects".
now it gives "= Objects" too.

![screenshot from 2018-10-15 22-20-15](https://user-images.githubusercontent.com/4154978/46973028-c0b62800-d0c8-11e8-9351-59bb0d7f335d.png)
![screenshot from 2018-10-15 22-20-36](https://user-images.githubusercontent.com/4154978/46973033-c3b11880-d0c8-11e8-8f12-d852a5aeb699.png)

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
А, нет. В справке сказано, что если строка поиска содержит "не слово", то опция `w` игнорируется.
Ничего исправлять не нужно

**Comment by Alexey-T** [comment]
а как сделано в других программах?

**Comment by kvichans** [comment]
Все игнорируют опцию, если она противоречит строке. Некоторые еще мониторят содержимое поискового запроса и автоматически переключают доступность кнопки.
