### ISSUE TITLE
Optimize report - dont duplicate lines

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#228]
скрин. тут можно вывести без дублей- посветить 2 раза в одной строке.
так можно делать если разность вхождений в строке не больше "порога"= например 40.

![screenshot from 2019-02-08 12-46-52](https://user-images.githubusercontent.com/4154978/52470655-da134080-2b9f-11e9-919e-8d9ae760c7a5.png)

**Comment by kvichans** [comment]
Уже есть такая настройка 
![default](https://user-images.githubusercontent.com/7419630/52470844-4f7f1100-2ba0-11e9-8bd6-14a5ec45a1d7.png)

**Comment by Alexey-T** [comment]
Хочется ее же для вывода когда файлы вложены в папки

**Comment by Alexey-T** [comment]
нашел.
