### ISSUE TITLE
Opt text

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#229]
Store separated history for pointed sessions/projects.
The history has values of the fields:
  Find what, Replace with, In files, Not in files, In folder
Each string in list is re-pattern to search in session/project file path.
Will be used first suitable string

- криво- опишите по русски плз?

**Comment by kvichans** [comment]
Опция позволяет хранить раздельные настройки (списки для "что искать", "исходная папка", "маска файлов" и пр.) для каждой сессии (или проекта) из перечисленных. Каждый элемент в этом перечисление - это шаблон (регулярное выражение), который сравнивается с полным путем к файлу сессии(проекта). Если путь текущей сессии(проекта) подходит под несколько шаблонов, то используется первый из них.

**Comment by Alexey-T** [comment]
Option allows to save separate search settings (search text, source folder, files mask etc) per each mentioned session or project. Each item in the option is RegEx, which is compared with the full path of session (project). First matched item is used.

**Comment by kvichans** [comment]
Спасибо
