### ISSUE TITLE
make lazy events

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#230]
[item400]
section=events
events=on_goto_def,on_click_dbl

- пригодядтся lazy events? думаю да. on_goto_def плаг может юзать только если уже открыт репорт.

**Comment by kvichans** [comment]
Поясните что это (или где про это читать)

**Comment by Alexey-T** [comment]
http://wiki.freepascal.org/CudaText_API#Lazy_events

**Comment by kvichans** [comment]
Прочитал. Не понял какую задачу это решает

**Comment by Alexey-T** [comment]
Если евент ленив, то он НЕ вызовется для НЕзагруженного плага

**Comment by kvichans** [comment]
Эти слова я видел в вики - но пока не понимаю их смысла.
А если событие вызывается для недозагруженного плага, то что происходит? Почему эта проблема вообще есть?
