### ISSUE TITLE
Idea from EmEditor 18.1

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#235]
Added the /Stop if number of matches reaches/ text box to the Find in Files and Replace in Files dialog boxes. The /Maximum Number of Files to Replace if Kept Open/ text box in the Search page of the Customize dialog box was deprecated.

**Comment by kvichans** [comment]
Требуется перевод

**Comment by Alexey-T** [comment]
В диалог ФИФ добавлена опция - Остановить когда найдено Н фрагментов
Вторая опц deprecated

**Comment by kvichans** [comment]
Такая опция уже есть и работает
![изображение](https://user-images.githubusercontent.com/7419630/55702956-e28dc900-59e0-11e9-85b6-8be7eaa88375.png)

**Comment by kvichans** [comment]
Нужен перевод первого поста

**Comment by Alexey-T** [comment]
Перевод я дал
лучше переименовать Firsts— Max matches

**Comment by kvichans** [comment]
Про "Вторая опц deprecated" не понял

**Comment by kvichans** [comment]
Я сам как раз второй опцией F пользуюсь чаще, чем первой M

**Comment by Alexey-T** [comment]
Про deprecated я сам не понял
