### ISSUE TITLE
I18n dir is empty

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#238]
ruboard - жалуются на пустую папку:

Я вижу папку py\cuda_find_in_files\lang\ru, но она пуста. Однако принцип вроде понял - подозреваю, что там должен лежать messages.pot

**Comment by kvichans** [comment]
Да, справедливая претензия. Я создал способ для перевода, но давно не выполнял сам перевод.
ToDo

**Comment by Alexey-T** [comment]
Fixed?

**Comment by kvichans** [comment]
Спасибо, что напомнили. Почти закончил, скоро опубликую
