### ISSUE TITLE
cannot edit option mark_style

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#240]
через длг не могу изменить опцию. она выделена на скрине.
![Screenshot from 2019-05-11 00-06-22](https://user-images.githubusercontent.com/4154978/57557049-5ffe7d80-7381-11e9-80bc-c6f85d6cf7e8.png)

**Comment by kvichans** [comment]
Так и задумано.
Диалог не дает средств для редактирования *подветок* **внутри себя**.
Вместо этого он дает *переход* внутрь `user.json`, где это можно сделать.
Умолчательное наполнение ветки нужно копировать из Комментария руками.

**Comment by Alexey-T** [comment]
'No user value for option fif_mark_style'-= вижу когда жму GoTo. баг?

**Comment by kvichans** [comment]
см..

**Comment by Alexey-T** [comment]
'GoTo'-  некрасиво, надо 'Edit...'

**Comment by kvichans** [comment]
Да, нужно доделать
