### ISSUE TITLE
wider help window

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#243]
что-то не то расширили (был такой виш)
![Screenshot from 2019-05-19 00-16-15](https://user-images.githubusercontent.com/4154978/57975057-556c6580-79cb-11e9-9632-676d5bbb7a08.png)

**Comment by kvichans** [comment]
Добавил еще 30 px

**Comment by Alexey-T** [comment]
намудрили - справа граница
![Screenshot from 2019-07-05 23-43-23](https://user-images.githubusercontent.com/4154978/60744468-ba314e80-9f7e-11e9-873f-31dae55ef225.png)

**Comment by kvichans** [comment]
да, спасибо за внимательность
поправил
опубликую позже
