### ISSUE TITLE
add option "Number of lines for multi-line regex"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#244]
Если трудно  искать multiline regex, хотя бы дайте опцию- subj- например если оно 4, то вы читаете для каждой строки ее + 3 следующ. строки (всего 4) и в этих 4 строках (склеиваем по \n) уже ищете.

применять опцию только если в начале regex стоит `(?s)` ?
или всегда применять? например для `aa[^;]+bb` тоже может найти multiline match.

наверно применять только если включен флаг поиска- по новой кнопкке около [.*].

я счас не смог найти что хотел- multiline Pascal code который бы начинался от if до raise.

**Comment by kvichans** [comment]
Да, трудно искать. А еще будет трудно показывать результат.
Подумаю об этом.
Вместо новой опции, можно задействовать существующие опции для Контекста - сколько строк до и после рассматривать.

Не понял что такое `(?s)` в Питоне. Может речь про `(?m)` - инлайн переключатель, аналог параметра `re.M (multi-line)` ?

**Comment by kvichans** [comment]
Ааа. Нашел `(?s)` - dot matches all

**Comment by kvichans** [comment]
Отказ. Причина: редкий запрос, большая переделка, проблемы представления результата
