### ISSUE TITLE
crash on "send results to tab" - Cud AV in ed.get_carets

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#252]
get_carets дает куде кривой хендл h (он дается из cudatext.py)- видно для убитого уже едитора вызываете.
[Kazam_screencast_00000.zip](https://github.com/kvichans/cuda_find_in_files/files/4708573/Kazam_screencast_00000.zip)

**Comment by kvichans** [comment]
Видео не дает идей, откуда сбой. ФИФ создал таб, наполнил его, пользователь закрыл ФИФ и ПОСЛЕ этого получил сбой. Пользователь (судя по видео) даже не вызвал команду из ФИФ для работы с этим текстом.

**Comment by Alexey-T** [comment]
не вызывал, после переноса- куд через 0.5с дает сбой.

**Comment by Alexey-T** [comment]
добавил  логинг в cudatext.py

    def get_carets(self):
        print('get_carets(%d)'%self.h)
        return ct.ed_get_carets(self.h)

при ПРОСТОММ вызове ed.get_carets лог пишет хендл=0.
при креше лог пишет

```
'only_frst': 0}
[ 1.06"]find_in_files:1201 ok files ==)[ 0.87"] #rsp_i={'cllc_files': 281, 'cllc_stopped': False, 'find_stopped': False, 'brow_files': 281, 'files': 102, 'frgms': 853}
[ 1.06"]report_to_tab:162 (==[ 0.00"] |paths|=102
[ 2.18"]report_to_tab:512 ==)[ 1.12"] stoped=False
get_carets(140513832489616)
get_carets(140513832489616)
get_carets(140513832489616)
```
 это точно ВАШ объект, из ФИФ.

и потом я убрал активные плагины- cuda_lint, cuda_hilite_occcur.

**Comment by Alexey-T** [comment]
еще подтв. что это ВАШ обьект Editor. при двигании каретки в окне ФИФ пишет такой то хендл. после креша с send-results-to-tab пишет в лог тот же хендл.

**Comment by Alexey-T** [comment]
и креша нет в Вин версии (wine). придется вам тестить под Лин. сори.

**Comment by Alexey-T** [comment]
нашел.
сделал лог у ВСЕХ ваших get_carets.
падает этот

```
        if not timer:
            # Direct call
            M.last_click_t  = now_t                         # time of user click
            if  M.rslt_timer_cb:
                return [] 
            M.rslt_timer_cb     = lambda tag: self.do_rslt_click(aid, ag, data, timer=True)
            app.timer_proc(app.TIMER_START, M.rslt_timer_cb, M.TIMER_DELAY)
            return []

        # Timer call
        pre_t   = M.last_click_t
        if  (now_t - pre_t) < M.SEL_TO_ACT_DELAY:           # too small pause after last user click
            return []                                       # wait next timer tick or user click
        assert M.rslt_timer_cb
        app.timer_proc(app.TIMER_DELETE, M.rslt_timer_cb, 0)
        M.rslt_timer_cb = None
        
        if aid=='rslt' and M.rslt_body!=M.DEF_RSLT_BODY:
            print('c6')
            row     = self.rslt.get_carets()[0][1]
```

видите тайймер??? вот по нему падает.

**Comment by kvichans** [comment]
Если разница только в Вин/Лин, то почему под подозрением ФИФ? Это же системный уровень

**Comment by Alexey-T** [comment]
не знаю. и Куд и ФИФ под подозрением. если репро нету

**Comment by Alexey-T** [comment]
когда вы получаете клик по едитору, вы пускаете timer.
вы делаете TIMER_STOP/TIMER_DELETE при закрытии окна?
если да, то куд получает тик? баг куд
если нет, баг ФИФ

**Comment by Alexey-T** [comment]
@kvichans  
куда получает on_click при Copy-res-to-tab. типа мой баг?

что делать-

1) делаем флаг
```
class FifD:
    status_s  = ''
    work = True
```
2)
юзаем его
```
    def do_rslt_click(self, aid, ag, data='', timer=False):  #NOTE: do_rslt_click
        if not self.work:
            return
```
3)
```
        elif tag=='rslt-move':
            self.work = False
            app.file_open('')
```

**Comment by kvichans** [comment]
Да, мутное место.
Мне совсем не понятно откуда может взяться "убитый едитор". 

ФФ при ESC ничего не удаляет 
- Внутренние редакторы ФФ только прячет, и готов показать их при следующем вызове.
- Внешний (в табе) ФФ создает, наполняет, но не хранит и не закрывает

**Comment by Alexey-T** [comment]
при ESC? мы про copy-res-to-tab. может вы форму убираете?

в Куд это поправил- теперь rt-click НЕ дает on_caret.
для 1.102 и ранее НУЖЕН фикс в ФИФ

**Comment by kvichans** [comment]
Фикс в Куд - ок
Что нужно исправить в ФФ?

**Comment by Alexey-T** [comment]
выше дал код- добавить флаг work

**Comment by kvichans** [comment]
Мне не понятно ни назначение, ни операции с этим флагом
- Что он [не]позволяет делать?
- Почему у него единственное (при выделении памяти под FifD) место присвоения True?

**Comment by Alexey-T** [comment]
он блокирует реакцию на on_caret в отчете если вызвана move-results-to-tab

после переоткытия диалога Фиф, клики работают и дают навигацию. зачем ещё делать True

**Comment by kvichans** [comment]
> он блокирует реакцию на on_caret в отчете если вызвана move-results-to-tab

Зачем? это чистый костыль без логического обоснования? 
И о каком "отчете" вы пишите? После move-results-to-tab есть две версии: одна внутри ФФ, другая в табе.

**Comment by Alexey-T** [comment]
Куд дергала on_caret после закрытия формы ФИФ- при убитом едиторе
work это фиксит

отчете - в форме ФИФ

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Про "убитый едитор" мне до сих пор не понятно. 
Как это он *убитый*, если при следующем показе ФФ он отображается и наполнен?

**Comment by Alexey-T** [comment]
не понятно.
в 1.102.2 это поправил, как ууже писал. так что больше копать не хочу...

**Comment by kvichans** [comment]
Закроем? Я не хочу править ФФ как вы предложили. Обновление Куд лечит - значит можно жить
