### ISSUE TITLE
Can't input "." in search field

### ISSUE THREAD

**Issue by thatfuckingbird** [kvichans/cuda_find_in_files#257]
I'm using the Qt5 version of CudaText on Linux with Find in Files 3.1.25
I can't enter the dot character (".") into the "Find what" field, because pushing dot toggles the regex button, even if the text input is focused.

**Comment by kvichans** [comment]
FiF3 is frozen. Use FiF4.
The problem was solved recently in FiF4.

**Comment by thatfuckingbird** [comment]
Tried installing FiF4, unfortunately I get an error when trying to open the search window. I'll open an issue in the FiF4 repo with details.
In the meantime, editing `cd_fi_in_fi.py` by changing `cap='&.*'` to `cap='.*'` solved the problem in FiF3.

**Comment by kvichans** [comment]
Yes. Your patch is good.

**Comment by Alexey-T** [comment]
@kvichans let's apply this patch?
