### ISSUE TITLE
opt not saved in Dlg

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#27]
тут все еще wordonly+treetype; 
а я 2 раза выбирал wordonly=off, treetype= без колонок (делал вызов Find in cur file, жал поиск "Undo", потом закрывал по х)

![ui](https://cloud.githubusercontent.com/assets/4154978/14751181/b7eb8404-08d9-11e6-9afd-489e6fd112a2.png)

**Comment by kvichans** [comment]
Пока копируются опции из локального поиска и насильно ставится тип отчета. В работе

**Comment by kvichans** [comment]
fix

**Comment by kvichans** [comment]
Копирование опций из локального поиска теперь можно включить в user.json
Тип отчета перестал навязываться
