### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#3]
Проверьте, что плагин "живой" не только у меня
1. Уже должен искать со всеми опциями
2. Пока результаты накапливаются, но никуда не выдаются. Только в статусе отображаются числа: найдено N фрагментов в M файлах.
3. Поиск можно прерывать по Esc. Если Esc на этапе сбора файлов, то результатов не будет. А если на этапе поиска фрагментов, то результаты - сколько успели найти.

Кроме того в консоли можно увидеть сколько времени занимали этапы "Сбор файлов" и "Поиск фрагментов"
`(:)=[ 1.45"]` - это про сбор файлов
`ok files ==)[ 2.68"]` - это про фрагменты

**Comment by Alexey-T** [comment]
Esc - Ok
