### ISSUE TITLE
hang: find in Lazarus dir

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#39]
finding:
![ff1](https://cloud.githubusercontent.com/assets/4154978/15143465/f4de83ae-16ba-11e6-911a-2a0c4e7c3223.png)

gives hang. 10s no update.
![ff2](https://cloud.githubusercontent.com/assets/4154978/15143475/01a240c6-16bb-11e6-9e3f-273c908669b7.png)

**Comment by kvichans** [comment]
Может в этой ветке есть циклы?

**Comment by Alexey-T** [comment]
нет.

**Comment by Alexey-T** [comment]
filenamager находит ок.

**Comment by kvichans** [comment]
Если другая прога умеет работать soft/hard links - она не циклится.
Как вы заключили что в этой папке нет soft/hard links?

**Comment by Alexey-T** [comment]
Dblcommander. в папке лаза вообще нет simlinks.

**Comment by kvichans** [comment]
1. soft/hard links ?
2. На Esc реагирует?

**Comment by Alexey-T** [comment]
1. linux. simlinks нету
2. нет
