### ISSUE TITLE
Inst using GH

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#4]
Хорошо бы плагин- указал Урл Гитхаба-
- он скачал плагин, перепаковал Зип, инсталлировал плагин (или просто инсталлировал)

**Comment by kvichans** [comment]
будет на этапе "беты"

**Comment by kvichans** [comment]
сори - дошло! - да хорошо бы такой

**Comment by Alexey-T** [comment]
Плис попробуйте! https://sourceforge.net/projects/cudatext/files/addons/plugins/plugin.Install_From_Github.zip/download

**Comment by kvichans** [comment]
Поставил, перезапустил, в Командах набрал git - пусто. Как? А вот и разгадка:
Install From Guthub
:)

**Comment by Alexey-T** [comment]
renamed
теперь как?

**Comment by kvichans** [comment]
подпись - мелочь
попробовал на чистом Куд. Сработало! Здорово
а что скачивает? исходники из последнего commit?

**Comment by Alexey-T** [comment]
ветку master :)

**Comment by kvichans** [comment]
Отлично!
