### ISSUE TITLE
wish. don't show er.

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#40]
лучше не показ. это.

Cannot read "/home/user/lazarus/test/manual/png/testsuite/s40i3p04.png" (encoding=None/['cp1252', 'UTF-8', None]): 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Cannot read "/home/user/lazarus/test/manual/png/testsuite/f01n2c08.png" (encoding=None/['cp1252', 'UTF-8', None]): 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by kvichans** [comment]
Совсем не сообщать о таких случаях? Или делать это кратко?

**Comment by Alexey-T** [comment]
совсем не сообщ.

**Comment by kvichans** [comment]
ок, будет опц с умолчанием "не сообщать"

**Comment by kvichans** [comment]
fix
