### ISSUE TITLE
report hangs for 30s

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#48]
Repl
![ff](https://cloud.githubusercontent.com/assets/4154978/15256642/7ff8ca2c-1953-11e6-8c9e-11ec89a7dc27.png)

hangs
![ff2](https://cloud.githubusercontent.com/assets/4154978/15256647/8493de96-1953-11e6-9336-f9340f608109.png)

repl is ok.

**Comment by kvichans** [comment]
Pls turn on Logger:

```
"fif_log_file":"t.log"
"fif_FNDLOG":true
```

and find last `path` in t.log. What's the path?

**Comment by Alexey-T** [comment]
It is folder /designer/ from laz. Can u test it?

**Comment by kvichans** [comment]
What's size? Can pass me?

**Comment by kvichans** [comment]
1) Повторил только Поиск (не Замену). FiF находит (за 0.4 сек) без малого 44 тыс фрагментов в **23 файлах** и после этого выводит отчет за 4 сек. 
2) Может ли разница "4 сек поиска" и "30 сек замены" быть из-за разных компов? Видимо может
3) При выводе отчета он не виснет, а глохнет, так как я поставил опрос Esc после каждых **37 файлов**.
4) Еще разбираюсь почему у меня при Замене получается "ничего не найдено".

**Comment by Alexey-T** [comment]
может, imo
НАдо пробовать как у меня- замену

**Comment by Alexey-T** [comment]
4) Отдел. баг

**Comment by kvichans** [comment]
4) Какая в действительности кодировка у *.pp и *.pas?

**Comment by Alexey-T** [comment]
/designer/- Ansi

**Comment by kvichans** [comment]
Ошибки плагина не было - это я чтобы не портить файлы поставил "заменить на" \1, а группу в "искать" не задал. Исправил.
Замены выполнились за 5.4 сек

**Comment by Alexey-T** [comment]
замена \w+
на __
замена ОК
report завис на 1мн

```
[28.77"]find_in_files:1643 ok files ==)[ 1.58"] #rsp_i={'cllc_files': 32, 'frgms': 87181, 'brow_files': 32, 'cllc_stopped': False, 'files': 32, 'find_stopped': False}
```

**Comment by kvichans** [comment]
он не завис! он работал - у меня эта замена закончилась через 7.6 сек

**Comment by kvichans** [comment]
Из инструкции к программе от фирмы IBM: "Если программа стала работать медленно, купите новый майнфрейм"

**Comment by Alexey-T** [comment]
замена- быстро. report- 50s.

**Comment by kvichans** [comment]
это нормально - 67 тыс строк оформить быстро нельзя

**Comment by kvichans** [comment]
Можно попробовать буферезовать заполнение отчета. ToDo
