### ISSUE TITLE
наезжают эл-ты

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#5]
![ff](https://cloud.githubusercontent.com/assets/4154978/14391148/640dbbf4-fdcb-11e5-8f97-1f55fedd1a1e.png)

**Comment by kvichans** [comment]
во-во
я старался - и все равно что-то не учел

**Comment by kvichans** [comment]
странно, что CurFolder выровнен с InFolder, а "w" c Find - нет

**Comment by Alexey-T** [comment]
- выводите БЕЗ десятых частей %
- можно выводить рез-т как json dump в Таб?
- more>>, less<< пробел нужен до << >>

**Comment by kvichans** [comment]
А-а-а, сообразил: это же новый контрол checkbutton - у меня для него еще не было замеров. Добавлю

**Comment by kvichans** [comment]
"наезжают" +"скрытые папки" - fix

**Comment by kvichans** [comment]
- _выводите БЕЗ десятых частей %_ - Это в статусе? Чтобы меньше мелькало? ок
- _можно выводить рез-т как json dump в Таб?_ - скоро будет нормальный вывод в таб
- _more>>, less<< пробел нужен до << >>_ - ок

**Comment by Alexey-T** [comment]
Над "All" combo нужен зазор,он липнет к едит

**Comment by kvichans** [comment]
лучше картинку - чтобы я понял про все контролы

**Comment by Alexey-T** [comment]
![ff2](https://cloud.githubusercontent.com/assets/4154978/14395154/2869122c-fde1-11e5-9b60-c73009af00b1.png)

еще 2 зазора малы

**Comment by kvichans** [comment]
ясно

**Comment by kvichans** [comment]
а почему на кнопках нет ускорителей? это всегда так?

**Comment by Alexey-T** [comment]
ОС прячет как и Вин

**Comment by kvichans** [comment]
Отображаются при зажатии Alt?

**Comment by Alexey-T** [comment]
да
