### ISSUE TITLE
Replacing umlauts does not work properly

### ISSUE THREAD

**Issue by Andreas123456** [kvichans/cuda_find_in_files#54]
Download the attached file and place it in a folder that will be searched later.

[Homeoffice - Arbeitsgericht stärkt Recht auf Telearbeit - SPIEGEL ONLINE.txt](https://github.com/kvichans/cuda_find_in_files/files/263937/Homeoffice.-.Arbeitsgericht.starkt.Recht.auf.Telearbeit.-.SPIEGEL.ONLINE.txt)

In the Find field, enter "schönsten" (without the quotes).
In the Replace with field, enter "äää" (without the quotes).
Set the Encoding field to "UTF-8, cp1252, <detected>".
Press the Replace button.
As a result, "schönsten" will be replaced with "\ä\ä\ä". The 3 backslash characters should not be there.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
What is value of option `.*`?

**Comment by Andreas123456** [comment]
.\* is not activated.
