### ISSUE TITLE
After replace, column and length of the new lines in the report are always 0

### ISSUE THREAD

**Issue by Andreas123456** [kvichans/cuda_find_in_files#55]
After replace, column and length of the new lines in the report are always 0. Example: (=77:  0:0)
The real (new) column and length values should be shown here.

**Comment by kvichans** [comment]
Now i dont know how to calculate possition for new fragment. I will think about it.

**Comment by kvichans** [comment]
I found trick to nearly solve problem. Report will join all _new fragments_ in line to one.
Example. 
Source line is **"1 a 2 a 3"**
`What` is **"a"**
`Replace with` is **"b"**
New line - **"1 b 2 b 3"**
_Proper_ report marks **two** fragments **"b"**
FiF _trick_ report marks **one** fragment **"b 2 b"**

**Comment by Andreas123456** [comment]
In my opinion, you should not / need not spend too much time to create a proper report after Replace. Other editors simply open a dialog box saying: "537 occurrences replaced", and that's all.

**If** you really want to create a detailed report, I would suggest the following: If the line contains only one fragment, then report it properly. (I understand that this is possible.) And if the the ontains more than one fragment, then report it with 0:0. Your "trick" looks more like a bug than "0:0".

**Comment by kvichans** [comment]
1) If line has only one replaced fragment tricked report is equal to proper.
If line has many ones -- both **0:0** and **joined fragment** are false. IMHO _joined_ is better because it shows narrowest area with replacements. 
2) If _the false_ is big problem for anybody FiF can use another mark style for _joined_

**Comment by Andreas123456** [comment]
1) Ok, I agree.
2) It's not a big problem, but yes, another mark style would be good.

**Comment by kvichans** [comment]
2) ToDo

**Comment by kvichans** [comment]
2) Fix. New styles:

```
    "fif_mark_true_replace_style":{"borders":{"bottom":"solid"}},
    "fif_mark_false_replace_style":{"borders":{"bottom":"wave"},"color_border":"#777"},
```
