### ISSUE TITLE
Wish: Support of special chars (\n \r \t...) as in SynWrite

### ISSUE THREAD

**Issue by Andreas123456** [kvichans/cuda_find_in_files#56]
It would be great if special chars (\n \r \t...) were supported for searching and replacing. SynWrite has a checkbox for that option in the dialog.

**Comment by kvichans** [comment]
No plans. 
Use reg.exp-option `.*`

**Comment by Andreas123456** [comment]
With regex option .\* you cannot add or remove line breaks, can you?

**Comment by kvichans** [comment]
Now \n and \r are not valid to FindInFind becouse no search "in whole file" - only in **each line of file**.
May be in future (not soon) "in whole file" will be added.

**Comment by Andreas123456** [comment]
Even with such an option (in whole file), it would not be possible to **add** a line break in the middle of a line. With SynWrite it's possible.

**Comment by Andreas123456** [comment]
I've just tried it out (I've replaced "," with "\n" and activated the regex option), and it did work. That's good! So I was wrong in my previous posting, and the only thing that's indeed missing is an option "in whole file".

**Comment by kvichans** [comment]
1) What is "it did work"? 
2) What is "in whole file"?

**Comment by Andreas123456** [comment]
> 1) What is "it did work"? 

Well, it worked as I wanted.

**_Before:_**
aaa,bbb
aaa,bbb
aaa,bbb
aaa,bbb
aaa,bbb

**_After:_**
aaa
bbb
aaa
bbb
aaa
bbb
aaa
bbb
aaa
bbb

> 2) What is "in whole file"?

That's the option you've mentioned yourself in your posting 2 days ago: "May be in future (not soon) "in whole file" will be added." From my understanding, it means that the whole file including the line breaks will be searched.

**Comment by kvichans** [comment]
1) What was state op `.*`?
2) Thanks. I recall. "In future" and "not soon" are actual.

**Comment by Andreas123456** [comment]
1) The regex option `.*` was activated.

**Comment by kvichans** [comment]
1) Then it is normal.
