### ISSUE TITLE
report fill

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#58]
Report /undo/es by NN steps. bad

**Comment by kvichans** [comment]
Подробнее опишите

**Comment by Alexey-T** [comment]
- make report (8 found mathces)
- press Undo
- undo works by 1 line

**Comment by kvichans** [comment]
И что? Это хорошо или плохо?

**Comment by Alexey-T** [comment]
undo buf ест память.

**Comment by kvichans** [comment]
И? Что дальше? У вас есть претензия/пожелание?
Плагин заполняет отчет _по строчно_, чтобы можно было прервать этот процесс. Вы предлагаете заполнять его одной API-командой?

**Comment by Alexey-T** [comment]
Да,юзать это http://wiki.freepascal.org/CudaText_API#lock.2Funlock

**Comment by kvichans** [comment]
А-а-а-а. ToDo

**Comment by kvichans** [comment]
Помогло? 
У меня наблюдаются странности:
- Undo теперь выполняется **одной** командой
- Redo - **несколькими**.

Как так?

**Comment by Alexey-T** [comment]
redo: потом посм.
