### ISSUE TITLE
Hanged "wait state"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#68]
поиск такой.
![fif1](https://cloud.githubusercontent.com/assets/4154978/15530922/56c29bd8-2268-11e6-8e20-fdd9444712b2.png)

в нем после Н секунд жму esc. потом идет отчет и ош.
после ош-ки редактор остался "wait..."

![fif2](https://cloud.githubusercontent.com/assets/4154978/15530926/63cba81a-2268-11e6-8639-86cacfea5472.png)

что такое TypeErr- непонятно

**Comment by kvichans** [comment]
Что теперь показывает лог?

**Comment by Alexey-T** [comment]
Log

```
[35.24"]collect_files:1714 >>1(:)how_walk={'root': '/home/user', 'skip_binr': False, 'sort_type': '', 'depth': -1, 'enco': ['cp1252', 'UTF-8', '<detected>'], 'only_frst': 0, 'skip_hidn': False, 'file_incl': '.*', 'skip_unwr': False, 'file_excl': ''}
[40.18"]    collect_files:1789 |rsp|, stoped=(19, True)
[40.18"]    1(:)=[ 4.93"]
[40.18"]find_in_files:1575 ?? files (==[ 0.00"] what_find={'word': False, 'repl': None, 'case': False, 'mult': False, 'reex': True, 'find': '\\w+'}
[41.47"]find_in_files:1656 ok files ==)[ 1.29"] #rsp_i={'cllc_files': 19, 'frgms': 21317, 'files': 19, 'find_stopped': False, 'brow_files': 19, 'cllc_stopped': True}
[41.47"]report_to_tab:847 (==[ 0.00"] |paths|=24
```

'wait' ввсе равно есть

**Comment by Alexey-T** [comment]
В выводе такое если сейвить-
....
....
60К файл, в конце
<.ICEauthority>: #14958

**Comment by kvichans** [comment]
1) Этот wait видимо натуральный - работа плагина еще не закончена (судя по логу и числу 14958 фрагментов в последнем файле)
2) Проверка Esc стоит после 37 файлов, до нее просто не доходит исполнение
3) В коде поставил

```
    rpt_ed.lock()
    try:
        <work loop>
    finally:
        rpt_ed.unlock()
```

Поэтому не вижу способа "не завершить". Но вижу, что может работать слишком долго.
4) Добавлю опций, чтобы проверку на Esс можно было делать чаще

**Comment by kvichans** [comment]
Пока добавил проверку на Esc при переборе внутри одного файла - один раз на каждые 1000 фрагментов.
Надеюсь теперь Esc у вас сработает

**Comment by Alexey-T** [comment]
работа плагина еще не закончена- закончена, тк. в консоли TypeError(same) и полминуты wait.

**Comment by kvichans** [comment]
уже на новой версии?

**Comment by Alexey-T** [comment]
да (есть finally)

**Comment by kvichans** [comment]
уже выложил более новую

**Comment by Alexey-T** [comment]
still bug

**Comment by kvichans** [comment]
в логе должно быть описание строки, где баг
есть?

**Comment by Alexey-T** [comment]
не вижу способа "не завершить".==  typeerror и вылет.

**Comment by kvichans** [comment]
Получил лог - не вижу в нем инфо о ошибке. Как вы его видите?

**Comment by Alexey-T** [comment]
консоль, строка "TypeError ......."

**Comment by kvichans** [comment]
в логе (почтой) этого не вижу

**Comment by Alexey-T** [comment]
скрин в начале.

**Comment by kvichans** [comment]
с тех пор в коде появился catch и печать стека - хочу узнать на какой строке кода ошибка

**Comment by Alexey-T** [comment]
лень проверять. но это явно был вылет в exception на уровне Куд. может баг мой
