### ISSUE TITLE
Under Windows, Replace changes all line endings in a file from UNIX to DOS

### ISSUE THREAD

**Issue by Andreas123456** [kvichans/cuda_find_in_files#70]
Under Windows, Replace changes all line endings in a file from UNIX to DOS. This is quite a nasty issue when you work with a version control system, because all lines of the file will be regarded as 'changed'.

Replace should always leave the type of line ending (DOS/UNIX/MAC) unchanged.

**Comment by kvichans** [comment]
You are right. ToDo

**Comment by kvichans** [comment]
@Andreas123456 Fixed?

**Comment by Andreas123456** [comment]
Yes, it's fixed. Thank you.
