### ISSUE TITLE
OsX dlg view

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#77]
- btn /current folder/. отрезано слева-справа по 4-8 пикс от "С" и "r"
- combo /encodings/. Не влезло, "US-ASCII, UTF-8, <..."
  (показано "...") нужно еще пикселей 30-50

**Comment by kvichans** [comment]
Лучше снимок, чем словами

**Comment by Alexey-T** [comment]
Не делается шот

**Comment by kvichans** [comment]
1. Добавил 9px. Помогло?
2. Контролы в колонке Skip/Sort/First/Enc теперь растягиваются вместе с редакторами (Find/In files/...)

**Comment by Alexey-T** [comment]
Ok-решено, жалко что ctrl/shift click не пашет в Мак

**Comment by Alexey-T** [comment]
Опс, пашут в мак
