### ISSUE TITLE
bt 1.1.2 Filter subfolders

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#78]
![fif-short](https://cloud.githubusercontent.com/assets/7419630/15984631/a412cc2a-2fdb-11e6-94f6-9d9b53d4a681.JPG)

1) Some redesign for Compact mode of dlg.
Buttons 
`Count`,`Preset`,`Adjust`,`Help` 
are hidden but its 
`Alt+T`,`Alt+S`,`Alt+J`,`Alt+H` 
are available.

2) Masks `In files`/`Not in files` now can **filter subfolders**.
A mask starts with `/` specifies to subfolder name.
Example.

```
        In file:       /a*  *.txt
        Not in file:   /ab*
        In folder:     c:/root
        In subfolders: All
```

Search will consider all `*.txt` files in folder `c:/root` and in all subfolders `a*` except `ab*`.

**Comment by Alexey-T** [comment]
It is nice feature, thanks
