### ISSUE TITLE
bt 1.1.2 Dlg Adjust

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#79]
New design (only design) of dialog Adjust
![fif-cust](https://cloud.githubusercontent.com/assets/7419630/16008880/ea9b34e0-3182-11e6-9d37-a511c34c9cc3.JPG)

**Comment by Alexey-T** [comment]
"OK" bettr, "Save" title is rare

**Comment by kvichans** [comment]
ok "OK"

**Comment by kvichans** [comment]
fix

**Comment by Alexey-T** [comment]
small edit
![fi](https://cloud.githubusercontent.com/assets/4154978/16009820/60c34a7a-318f-11e6-94eb-277a3fbd94f3.png)

**Comment by kvichans** [comment]
fix (никак не научусь предвидеть ваши гигантские контролы)

**Comment by Alexey-T** [comment]
(Делать запас 1.2 надо)
