### ISSUE TITLE
bt 1.1.4 Commands to jump between source fragments

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#80]
![fif-menu](https://cloud.githubusercontent.com/assets/7419630/16051811/07647ff4-326a-11e6-8e23-67dac151af2c.JPG)
1) New `Jump to *** fragment` commands.
2) `Jump to *** fragment` commands are available after user fills new report or calls any `Navigate to ***` command for old report file.
3) To call `Jump to *** fragment` commands report-tab shouldn't be active or even visible.
4) Source file will always open **in current group**.
5) `Jump to next file fragment` jumps to first fragment in next source file.
6) `Jump to next folder fragment` jumps to first fragment in first file in next folder.

**Comment by Alexey-T** [comment]
Pls file to readme.. 
[commands-jump-to.txt](https://github.com/kvichans/cuda_find_in_files/files/314554/commands-jump-to.txt)

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
Maybe Nagivate>> , Jump to>> menus ll be good.

**Comment by kvichans** [comment]
Это как? Еще один уровень подменю?

**Comment by Alexey-T** [comment]
да, если хотите.

**Comment by kvichans** [comment]
Это лишнее, так как
- в меню пока мало команд
- группы уже разделены
- без подменю удобнее вызывать
