### ISSUE TITLE
Bad report, replace ^ to __

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#83]
one tab:

```
tttt22
tttttttt33
```

Replace RE ^ to __
I cannot get idea of report. Report is OK? It strange :(

![re](https://cloud.githubusercontent.com/assets/4154978/16149582/d4294a76-34a2-11e6-92d4-1990c89f40c2.png)

**Comment by kvichans** [comment]
[x]Context ?
Что-то я не подумал, как будет работать Context при отчете о заменах.
Буду его для этой операции отключать

**Comment by Alexey-T** [comment]
Yep, [x]Contxt

**Comment by kvichans** [comment]
Лучше?

**Comment by Alexey-T** [comment]
Да, спс
