### ISSUE TITLE
Goto-defin. command

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#86]
For lexer "find results" good to handle goto-definition, I can jump to src file by it

![mm](https://cloud.githubusercontent.com/assets/4154978/16150349/b582fbf8-34a7-11e6-9678-95c2e142d13b.png)

**Comment by kvichans** [comment]
Как это реализовать?

**Comment by Alexey-T** [comment]
on_goto_def(self, ed_self): Called by go-to-definition command ...

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Проблема выбора: какую из команд `Перейти...` использовать?
Для меня наиболее естественная - `Открыть в соседней группе и остаться в отчете`.
Для Andreas, похоже, `Открыть в этой же группе и активировать`.

**Comment by Alexey-T** [comment]
Я юзаю только 1 группу (активировать)

**Comment by kvichans** [comment]
Да, нужно подстроиться под _обычное_ поведение goto-definition.
Будет переход в этой же группе

**Comment by kvichans** [comment]
fix

**Comment by Alexey-T** [comment]
Работает!!

**Comment by Alexey-T** [comment]
конфликт с PythonIntel. в лексе Пи плагин НЕ должен быть акт. вообще.

**Comment by kvichans** [comment]
Ничего не понял. Видимо вы мне не все детали рассказали. Что нужно кроме перехвата события? Проверять текущий лексер?

**Comment by Alexey-T** [comment]
нужно Не работать если не "ваш" лексер. Ваш "search results" и опция fif_nnnnn (если она есть).

**Comment by kvichans** [comment]
Отсек другие лексеры

**Comment by Alexey-T** [comment]
лучше еще- Method must return True if it handled command,

**Comment by kvichans** [comment]
разве True? Видимо False?

**Comment by Alexey-T** [comment]
почему false?

**Comment by kvichans** [comment]
Я вчера видел как plugin.Snippets в on_key возвращает False после работы

**Comment by Alexey-T** [comment]
тут не onkey.

**Comment by kvichans** [comment]
Разные смыслы у return?! Неожиданно

**Comment by Alexey-T** [comment]
Ну да

**Comment by kvichans** [comment]
Мне нужно делать "return True"?

**Comment by Alexey-T** [comment]
Если навигация идет

**Comment by kvichans** [comment]
поправил
