### ISSUE TITLE
Opt for log

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#89]
1.Нужна опция чтобы откл логи в консоли.
Опцию можно назвать fif_log
2. Хор имя для опц- fif_log_filename
wish: заюзать это имя

**Comment by kvichans** [comment]
Теперь при умолчательных настройках  user.json ничего в консоль не пишется.
Над всеми ключами для логов `fif_FNDLOG`, `fif_RPTLOG`, `fif_NAVLOG` появился над-ключ `fif_LOG`. Если над-ключ в состоянии false (это его умолчание), то ничего не пишется.

Имя ключа `fif_log_file` оставил прежнее.

**Comment by Alexey-T** [comment]
лучше назвать ключи fif_log_find fif_log_report fif_log_nav.

**Comment by kvichans** [comment]
Мне удобнее как сейчас
