### ISSUE TITLE
Лин показал- keyerror

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#9]
(может и консоль)
![py](https://cloud.githubusercontent.com/assets/4154978/14458975/30414126-00c6-11e6-9e55-59f96cfaecff.png)

**Comment by Alexey-T** [comment]
Искал строку \$\w+ в файлах *.pp в папке lazarus

**Comment by kvichans** [comment]
хорошо бы еще снимок диалога дать - другие настройки похоже мешают

**Comment by kvichans** [comment]
Попробуйте сразу на новой альфе
