### ISSUE TITLE
bt 1.1.8 New cmd "Repeat Finding by Report"

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#91]
New cmd `Repeat Finding by Report...`.
1) The cmd isnt shown in main menu. You can find it only in dlg **Cmds**.
2) To use the cmd **need to switch on** new option in `user.json`

```
    // Save all request details ("Find", "In folder", ...) in first line of result file. 
    // The info will be used in command "Repeat Finding by report"
    "fif_save_request_to_rpt":False,
```

3) If in a tab there are many reports **only the first** is used.

**Comment by Alexey-T** [comment]
False неверно, надо false.

**Comment by kvichans** [comment]
Спасибо

**Comment by Alexey-T** [comment]
Better name is "Repeat search for this report-tab"

**Comment by kvichans** [comment]
хорошо
