### ISSUE TITLE
Dont work on Mac

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#94]
deleted json config but dont help. FIF dont work on mac. On calling dlg: error about 'ascii' codec
OSX 10.8

![mac2](https://cloud.githubusercontent.com/assets/4154978/18256013/ada08f60-73c0-11e6-922d-8b3a8a25919a.png)

**Comment by kvichans** [comment]
Проблема с кодировкой файла `user.json`.
cudax пытается его прочитать с умолчательной (по locale) кодировкой `ascii`:
`401     usr_json    = os.path.join(app.app_path(app.APP_DIR_SETTINGS), 'user.json')`
`402     usr_opts    = _get_file_opts(usr_json)`
`366     opts    = _json_loads(open(opts_json).read(), **kw)`

Как узнать правильную кодировку файла `settings\user.json` ?
Как вы его в ядре читаете?
Может он на всех платформах в utf8 ?

**Comment by Alexey-T** [comment]
кажется, он всегда utf8.

**Comment by kvichans** [comment]
А в ядре есть явная кодировка при чтении?

**Comment by Alexey-T** [comment]
yes, utf8.

**Comment by kvichans** [comment]
Тут есть засада:
- Документация к Куд ничего не говорит о кодировке `user.json`.
- Куд помогает открывать этот файл, но не ограничивает пользователя - можно его править любым редактором.

В результате кодировка остается известна только пользователю?

**Comment by kvichans** [comment]
Нужно внести правку в cudax_lib - поставить явно utf8.

**Comment by kvichans** [comment]
Попробуйте с новым cudax_lib

**Comment by Alexey-T** [comment]
Now: solved, mac.
