### ISSUE TITLE
Press "w": dialog reopens

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#96]
Нажатия "w" "aA" ".*" переоткрывают длг...

**Comment by kvichans** [comment]
Да, это сделано специально для удобства пользователя. Переоткрытие позволяет переместить фокус на полезный контрол. Например, для продолжения ввода в edit.

## 

Я надеюсь, что развитие `dlg_custom` дойдет до состояния, когда _переоткрытие_ не будет мелькать. Уже писал, как это можно реализовать.
