### ISSUE TITLE
wish: use new API

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#97]
api PROC_GET_GUI_HEIGHT is for  Linux
(combobox dont fit).

![fif](https://cloud.githubusercontent.com/assets/4154978/19910182/db842926-a0a4-11e6-9d3a-0d6f0c50e6e4.png)

**Comment by kvichans** [comment]
Ура! Наконец-то не нужно будет в угадайку играть.
А на Маках будет давать реальные размеры контролов?

**Comment by kvichans** [comment]
Исключение комбобоксов сводит почти на нет всю идею АПИ

**Comment by kvichans** [comment]
Ох :(
Посмотрел новое АПИ. Оно ничем не поможет!
Сейчас доп.усилия прикладываются в другом месте: нужно добиться, чтобы тексты в соседних контролах оказались на одной гор.линии

---

Судя по снимку, сейчас на Лин есть проблема: подпись `In folder` не выровнена с содержимым edit-combo `/usr/lib` .
Нужно еще раз настроить подгоночные константы. 
- Запустите команду `Fit controls v-align for platform` из плагина `cuda_fit_v_alignments`. 
- Настройте выравнивание для edit-combo. 
- Передайте снимок.
- Попробуйте Save, перевызов Куд (или `reset plugin`). Ожидаю, что в ФиФ контролы сдвинутся.

**Comment by Alexey-T** [comment]
```
env:xfce4
check:-4
edit:-8
button:-4
combo_ro:-5
combo:-8
checkbutton:-5
linklabel:0
spinedit:-9
```

**Comment by Alexey-T** [comment]
FIF стало:
![scr2](https://cloud.githubusercontent.com/assets/4154978/19921129/f30cb256-a0f5-11e6-9304-a02cfd17fc7f.png)

**Comment by Alexey-T** [comment]
после смены "темы ОС" (опции ОС)
![scr3](https://cloud.githubusercontent.com/assets/4154978/19921269/99f2c574-a0f6-11e6-8911-616a09ac4baa.png)

**Comment by kvichans** [comment]
1. Похоже вы переехали на новый оконный менеджер: вместо `unity` теперь `xfce4`. Так?
2. Вижу - стало лучше
3. Очевидно, что нужно еще раздвинуть контролы, чтобы `All` не налезал и edit-combo не слипались. ToDo
4. Смена темы. Нужно еще раз вызывать `Fit controls`

**Comment by Alexey-T** [comment]
1- Точнее, я просто пробовал новый Лин (виртуалка)
может просто из высоты контрола считать aligns?

**Comment by kvichans** [comment]
Не получится по высоте контрола получить где в нем текст расположен

**Comment by Alexey-T** [comment]
можно считать, что "по центру"..

**Comment by Alexey-T** [comment]
выравнивать текст по буквам не особо нужно. а учесть высоту нужно.

**Comment by Alexey-T** [comment]
т.е., в строке контролы, высота контролов N1, N2, N3, выравнивать контролы относительно max(n1, n2, n3).

**Comment by kvichans** [comment]
Нет, я буду выравнивать по буквам

**Comment by kvichans** [comment]
Я добавлю вызов `Fit controls v-align for platform` в сам диалог ФиФ - по `Ctrl+Click` на `Adjust`
