### ISSUE TITLE
btn "Browse for folder" bug

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#99]
Linux, i typed in folder of file: ~/lazarus
(it is /home/nnn/lazarus, ~ is linux feature)
I press [browse]--- dialog dont show me ~/lazarus.

Wish: dialog shows folder /home/nnn/lazarus

**Comment by kvichans** [comment]
Если я правильно понимаю, `~` это макропеременная, которую нужно подменить перед вызовом через `os.path.expanduser(...)`.
ToDo

**Comment by kvichans** [comment]
Только не понятно нужно ли после выбора новой папки делать обратное действие - укорачивать путь с помощью `~`. И совсем не понятно, как это можно сделать.

**Comment by kvichans** [comment]
Сделал по-крестьянски: 
`path=path.replace(os.path.expanduser('~'), '~', 1) if path.startswith(os.path.expanduser('~')) else path`

**Comment by kvichans** [comment]
Потестируйте на Лине
Оказывается ~ работает и на Вин. Так что у себя я проверил

**Comment by Alexey-T** [comment]
> нужно ли после выбора новой папки делать обратное

нет!

**Comment by kvichans** [comment]
Почему "нет"? Я попробовал - понравилось.
Было: `~/smth`
Вызвал Browse, выбрал подпапку.
Стало: `~/smth/subfl`
Красота!

**Comment by Alexey-T** [comment]
работает.
